const ipsums = [
  { id: 1,
    name: 'Bob Ross',
    sentences: 
  [
  "Happy little trees Let's add a little more detail here There are no mistakes, just happy accidents",
  "Just beat the devil out of it Pretty little clouds Let's give him a friend",
  "We don't make mistakes, just happy little accidents Just relax and let it flow Painting should make you happy",
  "Happy little bushes You can do anything you want to do Let's get crazy Just go out and talk to a tree",
  "Let's have some fun today Believe that you can do it cause you can do it Don't be afraid to make big decisions",
  "You have to make these big decisions We need to put some highlights on these little trees",
  "I like to beat the brush You can create the world you want Find freedom on this canvas",
  "Use what you see, don't plan it I really recommend you use odorless thinner or your spouse is gonna run you right out into the yard",
  "Just let it happen Maybe there's a happy little waterfall happening over here",
  "Every day is a good day when you paint Let's make some happy little clouds in our world",
  "You can put as many or as few as you want Get tough with it Just let your imagination go wild",
  "Maybe there's a little bush that lives right there You can do it There's nothing wrong with having a tree as a friend",
  "Just let your brush dance around and play You can have anything you want in this world",
  "Just let it flow, it has its own life The only thing worse than yellow snow is green snow",
  "You can create anything that makes you happy Let's put a happy little sky in here",
  "Exceedingly good time This is your world Don't be afraid to make these big decisions",
  "We don't have mistakes here, we just have happy accidents In your world, you can do anything",
  "Decide where your little footy hills live That's a crooked tree. We'll send him to Washington",
  "Just make little strokes like that This is happy place, little squirrels live here and play",
  "You can do anything here You can create anything that makes you happy In your world, you can do anything",
  "You have to make these big decisions The more we do this - the more it will do good things to our heart.",
  "We don't make mistakes, just happy little accidents. There are no limits here. You start off by believing here.",
  "Let's build some happy little clouds. You have to make a decision; you have to choose.",
  "We don't have anything but happy trees and clouds. Let your imagination be your guide.",
  "You need the dark in order to show the light. Anything that you believe you can do strong enough, you can do.",
  "We want happy paintings. Happy paintings. If you want sad things, watch the news.",
  "You can do anything here. This is your world. I like to beat the brush.",
  "Gotta give him a friend. Like I always say, 'Everyone needs a friend.' It's a good way of getting rid of all your anxieties and hostilities.",
  "Just let it go. Let it go like you wouldn't believe. Let your imagination be your guide.",
  "All kinds of happy little splashes. That's a crooked tree. We'll send him to Washington.",
  "We don't make mistakes. We have happy accidents. Talent is a pursued interest. Anything that you're willing to practice, you can do.",
  "You can do it. You can do it. You can do it. Just go out and talk to a tree. Make friends with it.",
  "We don't need any guidelines or formats. All we need to do is just let it flow straight from your heart.",
  "Every highlight needs its own personal shadow. We don't have anything but happy trees here.",
  "There is no right or wrong - as long as it makes you happy and doesn't hurt anyone.",
  "Don't be afraid to go out on a limb. That's where the fruit is. This is the fun part.",
  "Trees get lonely too, so we'll give him a little friend. There's nothing wrong with having a tree as a friend.",
  "Remember, this is your world. You're the creator. You have freedom on this canvas.",
  "Just let this happen. We just let this flow right out of our minds. A tree needs to be your friend if you're going to paint him.",
  "If you don't think every day is a good day, just try missing one. It's life. It's interesting. It's fun.",
  "In painting, you have unlimited power. You have the ability to move mountains.",
  "This is the light area. So we'll take our lightest light and put it in here.",
  "It's a very cold picture, I may have to go get my coat. Every day is a good day when you paint.",
  "You can do anything you want to do. This is your world. The secret to doing anything is believing that you can do it.",
  "If you do too much, it's going to lose its effectiveness. Just relax and let it flow. That easy.",
  "It's hard to see things when you're too close. Take a step back and look.",
  "And maybe, maybe, maybe... Maybe there's a happy little bush that lives right there.",
  "In your imagination, you can go anywhere you want.",
  "If there's two big trees invariably sooner or later there's gonna be a little tree.",
  "Water's like me. It's laaazy... Boy, it always looks for the easiest way to do things.",
  "I'm sort of a softy, I couldn't shoot Bambi except with a camera.",
  "You can do anything here. So don't worry about it. The least little bit can do so much.",
  "I think there's an artist hidden at the bottom of every single one of us.",
  "You can get away with a lot. We don't have to be committed. We are just playing here."  
]
  },
  { id: 2,
    name: 'Boston', 
    sentences: 
    [
    "Pahk the cah in Hahvahd Yahd. Wicked smaht It's wicked pissah Are you going to Dunkies?",
    "Did you catch the Sox game? We'll hit up Fenway Pahk Let's go grab a lobstah roll I'm wicked hungry",
    "Don't be a masshole I can't believe it's already pahstin' time The T is always delayed",
    "This weathah is wicked unpredictable My grandma makes the best chowdah The Red Sox are wicked good this year",
    "The Bruins got a wicked tough schedule. You can't drive in the North End, it's a maze",
    "I'm wicked excited for St. Paddy's Day It's freezing in Southie That parking spot is worth gold",
    "The Zakim Bridge is wicked awesome. Don't forget to grab a cannoli in the North End",
    "The chowdah at Legal Sea Foods is wicked tasty. You need a permit to park on this street.",
    "I'm heading to the Cape for the weekend. Pahkin' is an art form in Boston.",
    "I'm wicked pissed off about the traffic. Fenway Pahk has the best hot dogs. The Harbor Islands are a hidden gem.",
    "I'm wicked proud to be from Boston. We're going to Southie for St. Paddy's.",
    "I love the Charles Rivah Esplanade. I can't get enough of those lobstah rolls.",
    "The Boston Marathon is a wicked big deal. The Common is the perfect spot for a picnic.",
    "The Pru is wicked tall. The traffic in Boston is legendary. I need a cuppa regulah coffee.",
    "The Swan Boats in the Public Garden are iconic. I'm going to grab a frappe at Friendly's.",
    "I love walkin' the Freedom Trail. The pahking garages are wicked expensive. The Boston Tea Party was a wicked cool event.",
    "Boston drivers are crazy. I'm goin' down the Cape this weekend. The Boston accent is wicked distinct.",
    "I'll meet ya at the Bunker Hill Monument. We'll tailgate before the Patriots game.",
    "The Hatch Shell is the place to be for concerts. I need to get me a lobstah bib.",
    "I'm wicked bummed the Celtics lost. Cheers is a wicked popular spot in Boston.",
    "Pahk the cah in Hahvahd Yahd! It's wicked hot out today, kid! I'm so hungry, I could eat a whole lobster roll!",
    "This traffic is worse than the Green Line during rush hour! Hey, guy, wanna grab a Dunkies?",
    "Tom Brady is the GOAT, no doubt! I'm not angry, I'm just passionate!",
    "You can't retahd the rules of baseball! I need a regulah cup of chowdah! The weather changes more than my socks in New England!",
    "I'll take a frappe ovah a milkshake any day! I've got the Patriots game on, don't bothah me!",
    "I love fall, the leaves look wicked nice! I'm wicked smaht, just like Matt Damon!",
    "Let's head down to the Cape and hit the beach! The Red Sox are having a wicked good season!",
    "I can't find my cah keys, again! I'll have a cold beeah and some clam chowdah!",
    "I won't give up my seat on the T for no one! I'll take extra cheese on my pizza, please!",
    "This traffic makes me wanna chuck my phone out the window! I'm gonna go catch some rays at Revere Beach!",
    "The accent is wicked hahd to understand, I know! I'll have a lobstah roll with buttah, not mayo!",
    "The Bruins are gonna win the Cup this year! You can't beat a Fenway Frank at a Sox game!",
    "I'll take a regulah coffee, none of that fancy stuff! I'm wicked excited for the concert at the Garden!",
    "The Zakim Bridge is a wicked cool sight at night! I've never met a lobster I didn't like!",
    "I need a sweatah, it's getting chilly out! Cheers to Sam Adams, our favorite local brew!",
    "The Tea Party was a wicked important event! I'm not yelling, this is just how we talk!",
    "I'll take a cannoli from the North End, please This is a wicked awesome view of the city!",
    "I'm gonna pahk my cah in the Hahvahd Yahd! Let's go down to the harbor and watch the boats!",
    "I love walking the Freedom Trail on weekends! The Green Monster is a legendary Fenway landmark!",
    "This is a wicked big portion of clam chowdah! I can't wait for the next Patriots game, kid!",
    "The Boston accent is wicked hahd to imitate! I'm not drunk, just having a few beeahs!",
    "I'm gonna take a trip up to Maine for lobstah! This lobster bisque is wicked delicious!",
    "I'll have a roast beef sandwich, extra sauce! Let's hit the Cape and go beachcombin'!",
    "I'm heading to the packie for some beeah and wine! The Swan Boats are a wicked fun ride in the Common!",
    "I'll take a slice of Boston cream pie for dessert! Don't pahk in front of that fire hydrant!",
    "I'm going to the Cape to escape the city, guy! This is a wicked funny movie, it's got me laughin' wicked hahd!",    
    "This weather is straight-up New England The Citgo sign is the heart of Boston",
    "Pats fans are wicked passionate I love the smell of Fenway Franks in the air",
    "I'm heading down to Quincy Market for lunch I need a bubble tea from Allston",
    "I saw a squirrel steal someone's Dunkin' bagel The BAA half marathon is a wicked hahd race",
    "It's colder than a Bruins game in January I'm going to catch a flick at the Coolidge Corner Theatre",
    "My neighbor shovels snow like a boss I'm gonna get some wicked good Italian food in the North End",
    "This road is bumpier than the Green Lie I'm wicked excited for the St. Patrick's Day parade",
  ]
  }, 
  { id: 3,
    name: 'Mr Rogers', 
    sentences: 
    [
    "I like you just the way you are. There's only one person in the whole world like you.",
    "You make each day a special day just by being you. You've made this day a special day by just your being you.",
    "You are the only one like you. It's such a good feeling to know you're alive.",
    "There's no person in the world exactly like you. I'm proud of you for the times you've said 'I'm sorry.'",
    "It's not the honors and the prizes and the fancy outsides of life which ultimately nourish our souls.",
    "You've made this day a special day just by being you. When we love a person, we accept him or her exactly as is.",
    "It's you I like. I'm proud of you for the way you've grown.I'm glad we're together.",
    "There's no person in the whole world like you, and I like you just the way you are.",
    "I like you just the way you are, and I hope you like me just the way I am.",
    "You're the only person who can be you. You're special to me.You are special.",
    "There's nobody else in the world who can do it. When we love somebody, we give them the strength to grow.",
    "You've made this day a special day by just your being you. You've made this day a special day just by your being you.",
    "It's such a good feeling, a very good feeling, to know that we're lifelong friends.",
    "It's a beautiful day in this neighborhood. You are my friend. You are special.",
    "You've made this day a special day by just your being you. There's no person in the whole world like you, and I like you just the way you are.",
    "It's you I like. It's not the things you wear. It's not the way you do your hair, but it's you I like.",
    "I'm proud of you for the way you're growing, even though sometimes growing takes a long time.",
    "I hope you're proud of yourself for the times you've said 'yes,' when all it meant was extra work for you and was seemingly helpful only to somebody else.",
    "You've made this day a special day by just your being you. I'm glad we're friends.",
    "You're the only one who can fill your space in this world. Nobody else could do it.",
    "You are special, and I can't think of anything else quite like you. You're growing every day. I'm proud of you.",
    "I think the best thing we can do is to let people know that each one of them is precious.",
    "The greatest gift you ever give is your honest self. You are special, and I like you.",
    "Discovering the truth about ourselves is a lifetime's work, but it's worth the effort.",
    "You've made this day a special day by just your being you. You are special, and I'm glad you're my friend.",
    "I like you as you are. Exactly and precisely. You always make each day such a special day.",
    "There's nobody else in the whole world who's exactly like you. Nobody else in the world can do what you can do.",
    "You've made this day a special day by just your being you. The greatest gift you ever give is your honest self.",
    "It's you I like. It's not the things you wear. It's not the way you do your hair, but it's you I like.",
    "You've made this day a special day by just your being you. There's no person in the whole world like you, and I like you just the way you are.",
    "I'm proud of you for the times you've been brave. I like you as you are. Exactly and precisely.",
    "The world needs a sense of worth, and it will achieve it only by its people feeling that they are worthwhile.",
    "You've made this day a special day just by being you. There's no person in the whole world like you, and I like you just the way you are.",
    "You are special. I like you just the way you are. There's no person in the whole world like you.",  
    "I'm proud of you. You make each day a special day just by being you. It's a beautiful day in the neighborhood.",  
    "Won't you be my neighbor? I've always wanted to have a neighbor just like you. You are valuable.",  
    "You make every day a special day just by being you. It's you I like. You're growing every day.",  
    "I'm grateful to have you as my friend. I'm glad we're together. You are lovable.",  
    "I like to be told when you're mad at me. You're a very special person. I'm glad you're you.",  
    "You've made this day a special day by just your being you. I like how you express the things that you feel.",
    "There's no one else in the world who is exactly like you. You always make each day such a special day.",  
    "I like you inside and out. I like it when you tell me how you feel. I like you as you are.",  
    "I like you just the way you are, and I hope you'll like me just the way I am.",  
    "You've made this day a special day just by you being you. I'm glad we're here together.",  
    "I appreciate you. You're my friend. I'm glad we're friends. You make today a special day.",  
    "You are my friend. You're the only person who can be you. You're important.",
    "I like the way you are right now. You're the only one in the whole world who's exactly like you.",  
    "I'm happy to see you. I like you every way you are. You are special and you are my friend.",  
    "I like you today, and I like you tomorrow. You make every day special just by being you.",  
    "I'm glad to know you. I'm so glad we're together. You are precious to me.",  
    "You are special to me. I'm glad you're my friend. You're the only one like you.", 
    "I like you just the way you are, and I hope you like me just the way I am.",  
    "I like how you show the feelings you feel I like everything about you.",  
    "You've made this day a special day by just being you. I appreciate you. You make every day a special day"
  ]
  },
  { id: 4,
    name: 'Cowboy', 
    sentences: [
    "Happy trails! Ride 'em cowboy! Saddle up and hold on tight. There's a new sheriff in town.",
    "Yeehaw! Keep your powder dry. Don't squat with your spurs on. Ain't nothin' better than the smell of leather.",
    "Never trust a man who doesn't wear a hat. This town ain't big enough for the both of us.",
    "Time to hit the dusty trail. Don't count your chickens before they're hatched.",
    "As the crow flies. Easy as pie. Hold your horses. Tougher than a two-dollar steak.",
    "Giddy up! Don't fence me in. The early bird gets the worm. Lasso your dreams.",
    "Don't talk big on an empty belly. Take the bull by the horns. Home on the range.",
    "Riding off into the sunset. The wind at your back and the sun on your face. A cowboy is a man with guts and a horse.",
    "Live by the saddle, die by the saddle. Stay on the straight and narrow. Ain't no use in frettin' over spilled milk.",
    "The only way out is through. Rope 'em, tie 'em, brand 'em. Give it all you've got, then give some more.",
    "Mind your Ps and Qs. Don't let the dust settle under your boots. Ain't no sense in bawlin' over spilt milk.",
    "Ain't no rest for the wicked. Never look a gift horse in the mouth. The old cowpoke still has some tricks up his sleeve.",
    "Saddle sores and calloused hands make a cowboy. Better to be a has-been than a never-was.",
    "Luck is what happens when preparation meets opportunity. Don't let your mouth write checks your body can't cash.",
    "Steady as she goes. Like a tumbleweed in the wind. The sun's always shining above the clouds.",
    "When in doubt, let your horse do the thinkin'. Don't squat on your spurs.",
    "Ride the high country. Life is tough, but cowboys are tougher. Never give a wolf an even chance.",
    "Stay true to your roots. Saddle sores are badges of honor. Well, butter my biscuit!",
    "Don't squat with your spurs on. If you think you're a cowboy, I've got a bridge to sell you.",
    "I'm as nervous as a long-tailed cat in a room full of rocking chairs.",
    "She's purtier than a speckled pup in a red wagon. If you can't ride, you can always fall with style.",
    "Don't worry, cowboy, just saddle up and ride. He's all hat and no cattle.",
    "I'm so broke I can't even pay attention. Don't let your mouth write a check your spurs can't cash.",
    "It's so dry, the trees are bribing the dogs. I'm sweating like a sinner in church.",
    "He's about as useful as a screen door on a submarine. She's tougher than a cowboy's coffee.",
    "That horse is slower than molasses in January. He's got more wrinkles than a rodeo clown's shirt.",
    "I'm as confused as a cow on astroturf. Well, knock me down and steal my teeth!",
    "He's crazier than a rodeo bull with a bee in his saddle. I'm happier than a tornado in a trailer park.",
    "He's so country, he thinks a seven-course meal is a possum and a six-pack. I'm as busy as a one-legged man in a butt-kicking contest.",
    "That's slicker than a greased pig at a county fair. He's as handy as a pocket on a shirt.",
    "I'm as lost as a goat on roller skates. She's got a smile that could charm the boots off a rattlesnake.",
    "He's slower than a herd of turtles stampeding through peanut butter.",
    "I'm as happy as a tick on a fat dog. Well, I'll be a monkey's uncle! He's sweeter than a jar of molasses.",
    "I'm dumber than a sack of hammers. She's sharper than a cowboy's spur. He's happier than a pig in slop.",
    "I'm madder than a wet hen. That's lower than a snake's belly in a wagon rut.",
    "He's slicker than a snake oil salesman. I'm as jumpy as a cat on a hot tin roof.",
    "She's wilder than a bucking bronco at the rodeo. He's dumber than a box of rocks.",
    "I'm grinnin' like a mule eatin' briars. That's harder to find than a needle in a haystack.",
    "He's got more nerve than a toothache. I'm as tired as a dog in a flea circus.",
    "She's faster than a cheetah on roller skates. He's crazier than a bull in a china shop.",
    "I'm as hungry as a wolf in a sheep pen. That's funnier than a clown in a saddle.",
    "He's got more stories than a rodeo cowboy.I'm as stubborn as a mule with a nail in its hoof.",
    "She's as feisty as a wild mustang. He's happier than a tornado in a trailer park.",
  ]
  },
  { id: 5,
    name: 'Gamer', 
    sentences : [
    "Game on! Level up! Stay frosty! Ready, set, go! Time to pwn! Get in the game! Keep calm and game on.",
    "Press start to begin. Respawn in progress. Victory awaits! Game over, man! The grind never ends. Aim high, hoot true.",
    "Gameplay or it didn't happen. Born to play. No lag, no mercy.",
    "One more round! Can't stop, won't stop. Game face on. In pixels we trust. Rage quit in 3... 2... 1...",
    "The legend begins. Gameplay is my cardio. Reload, reload, reload. Achievement unlocked!",
    "Ready for epicness! Glitch in the matrix. Play like a pro. Bring on the challenge!",
    "Game night is the best night. Game on! Level up! Stay frosty! Ready, set, go! Time to pwn!",
    "Get in the game! Keep calm and game on. Press start to begin. Respawn in progress.",
    "Victory awaits! Game over, man! The grind never ends. Aim high, shoot true.",
    "Gameplay or it didn't happen. Born to play. No lag, no mercy. One more round! Can't stop, won't stop.",
    "Game face on. In pixels we trust. Rage quit in 3... 2... 1... The legend begins.",
    "Gameplay is my cardio Reload, reload, reload. Achievement unlocked! I'm the king of the kill! I'm the gaming champion!",
    "Ready for epicness! Glitch in the matrix. Play like a pro. Bring on the challenge!",
    "Game night is the best night. Enter the virtual realm. Keep your friends close and your enemies laggy.",
    "Gaming is life. Noob, but learning. Game over? Just one more time. Welcome to the digital battlefield.",
    "Power-up and dominate. Keep your head in the game. Unlock your potential. Gaming: where dreams come true.",
    "Pixelated adventures await. Game over is not an option. Game hard or go home. Respawn and conquer.",
    "Game with passion. Stay sharp, stay alive. Gameplay is an art. It's dangerous to go alone!",
    "Play smarter, not harder. Leveling up in progress. The gamer's creed: Play. Explore. Conquer.",
    "1v1 me, bro! GGWP (Good Game, Well Played) I'm on a killing spree! Get rekt! Noob!",
    "I need healing! Pew pew! I'm the ultimate boss! AFK Boost me, please! I'm going for the high score!",
    "I can't believe I lost! Time to level up! Teamwork makes the dream work! Just one more turn...",
    "I'm in the zone! I'm the king of this game! I'm going pro! I'm on fire! Headshot!",
    "Let's rush B! I can't stop playing! I'm the MVP (Most Valuable Player)!",
    "This game is so addictive! Where's the save point? I'm grinding for loot! Boom! Headshot!",
    "I'm the master of this game! I'm getting better every day! I'm unstoppable! The lag killed me!",
    "Let's get that W (Win)! I'm gonna rage quit! I'm living the gamer life!",
    "Time to respawn! This game is so intense! I'm top of the leaderboard! I'm gonna speedrun this!",
    "I'm a gaming prodigy! I need better gear! I'm on the final level!",
    "I'm getting the high score! Let's camp and snipe! This game is my life! I'm going for the platinum trophy!",
    "I'm a gaming god! I'm going pro in esports! I'm gonna stream this game! Noob tube!",
    "Get good or go home! I'm just here to have fun and kick some virtual butts.",
    "Pew pew pew! I don't rage quit, I tactical retreat. I've got the high ground!",
    "One more round, and then I'm done... maybe. GG, well played! Fear the no-scope! Just one more level...",
    "Time to respawn and get back in the action. No lag, no problem. I'm the ultimate gamer, watch and learn.",
    "Headshot! You didn't see that coming. Eat, sleep, game, repeat. I'm a gaming machine!",
    "I'm on fire! New game, who dis? 360 no-scope, baby! A gamer never dies; they just respawn.",
    "I'm not addicted; I just can't stop gaming. In the game of life, I'm level 99.",
    "I play like it's my last day on Earth. I'm too old for this... wait, no, I'm not!",
    "Gaming is life, the rest is just details. I don't need a life; I'm a gamer. I don't sweat; I glisten.",
    "No challenge is too great for me. Victory tastes sweeter when it's hard-earned.",
    "You mess with the gamer, you get the skills. Fear my gaming prowess! Game over, man, game over!",
    "I'm in the zone. Stay calm and keep gaming. Level up achieved!",
    "I'm like a ninja, but with a controller. There's no respawn in real life, so make it count.",
    "I'm the boss of this game. Noobs, beware! My thumbs are weapons of mass destruction.",
    "Just another day in the virtual world. I've got mad skills and a bag of chips.",
    "I'm on a winning streak! Excuse me while I dominate this game. I'm a gamer, not a quitter.",
    "My reflexes are second to none. I was born to play this game. In the game of victory, there are no losers.",
    "I'm not camping; I'm just strategically waiting. I'm not a button-masher; I'm a precision player.",
    "The gaming gods smile upon me. I don't need a map; I know this game like the back of my hand.",
  ]
  },
  {id: 6,
    name: 'Harry Potter', 
    sentences: [
    "I solemnly swear that I am up to no good. Expecto Patronum! After all this time? Always.",
    "It does not do to dwell on dreams and forget to live. The ones that love us never really leave us.",
    "Dark times lie ahead of us, and there will be a time when we must choose between what is easy and what is right.",
    "Happiness can be found even in the darkest of times if one only remembers to turn on the light.",
    "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
    "Not all treasure is silver and gold, mate. Help will always be given at Hogwarts to those who ask for it.",
    "We've all got both light and dark inside us. What matters is the part we choose to act on.",
    "To the well-organized mind, death is but the next great adventure. The ones that love us never really leave us.",
    "It is our choices that show what we truly are, far more than our abilities. Dobby is a free elf!",
    "Words are, in my not-so-humble opinion, our most inexhaustible source of magic. Yer a wizard, Harry.",
    "It does not do well to dwell on dreams and forget to live. The best of us sometimes eat our words.",
    "We must all face the choice between what is right and what is easy. We've got a Seeker!",
    "Just because you have the emotional range of a teaspoon doesn't mean we all have.",
    "It matters not what someone is born, but what they grow to be. You're a wizard, Harry.",
    "Wit beyond measure is man's greatest treasure. To the well-organized mind, death is but the next great adventure.",
    "Numbing the pain for a while will make it worse when you finally feel it. After all this time? Always.",
    "We're all human, aren't we? Every human life is worth the same and worth saving.",
    "Differences of habit and language are nothing at all if our aims are identical and our hearts are open.",
    "It takes a great deal of bravery to stand up to your enemies, but a great deal more to stand up to your friends.",
    "It is the unknown we fear when we look upon death and darkness, nothing more. Turn to page 394.",
    "Curiosity is not a sin, but we should exercise caution with our curiosity. I open at the close.",
    "Indifference and neglect often do much more damage than outright dislike. I must not tell lies.",
    "We must try not to sink beneath our anguish, Harry, but battle on. I am not worried, Harry. I am with you.",
    "It is the quality of one's convictions that determines success, not the number of followers.",
    "Things we lose have a way of coming back to us in the end, if not always in the way we expect.",
    "Age is foolish and forgetful when it underestimates youth. It is impossible to manufacture or imitate love.",
    "We are only as strong as we are united, as weak as we are divided. When in doubt, go to the library.",
    "It is a curious thing, Harry, but perhaps those who are best suited to power are those who have never sought it.",
    "It is a strange thing, but when you are dreading something, and would give anything to slow down time, it has a disobliging habit of speeding up.",
    "It is the unknown we fear when we look upon death and darkness, nothing more. Dobby is a free elf!",
    "We do not need magic to change the world. We carry all the power we need inside ourselves already.",
    "You sort of start thinking anything's possible if you've got enough nerve. The wand chooses the wizard.",
    "It is the unknown we fear when we look upon death and darkness, nothing more. We've got a Seeker!",
    "Indifference and neglect often do much more damage than outright dislike. Turn to page 394.",
    "There are some things you can't share without ending up liking each other, and knocking out a twelve-foot mountain troll is one of them.",
    "The mind is not a book, to be opened at will and examined at leisure. Fear of a name only increases fear of the thing itself.",
    "Greatness inspires envy, envy engenders spite, spite spawns lies. I solemnly swear that I am up to no good.",
    "To have been loved so deeply, even though the person who loved us is gone, will give us some protection forever.",
    "We've all got both light and dark inside us. What matters is the part we choose to act on.",
    "It is our choices, Harry, that show what we truly are, far more than our abilities.",
    "To the well-organized mind, death is but the next great adventure. Nitwit! Blubber! Oddment! Tweak!",
    "Numbing the pain for a while will make it worse when you finally feel it. You're just as sane as I am.",
  ]
  },
  { id: 7,
    name: 'Hipster', 
    sentences: [
    "Craft beer irony 8-bit.Tote bag biodiesel flannel. Organic kale chips ennui.",
    "Polaroid DIY fanny pack. Farm-to-table tattooed quinoa. Artisanal typewriter messenger bag.",
    "Vinyl sustainable locavore. Beard trust fund chambray. Vintage bicycle PBR&B. Avocado toast cardigan aesthetic.",
    "Sustainable leggings gluten-free. Hand-poured soy candle heirloom. Meditation kombucha Tumblr.",
    "Roof party YOLO cold-pressed. Mustache cronut ethical. Vegan brunch plaid. Lumbersexual bespoke dreamcatcher.",
    "Artisan coffee skateboard. Edison bulb bicycle rights. Taxidermy banh mi flexitarian.",
    "Gluten-free VHS sriracha. Freegan selvage kale chips. Chia seed irony messenger bag.",
    "Vice master cleanse cray. Portland slow-carb activated charcoal. Narwhal fashion axe kitsch.",
    "Ethical drinking vinegar cliche. Pitchfork irony hoodie. Copper mug succulents. Fingerstache PBR&B biodiesel.",
    "Dreamcatcher Helvetica normcore. DIY craft beer forage. Skateboard tousled tofu. Lo-fi four loko umami.",
    "Sriracha swag selfies. Cold-pressed shabby chic. Single-origin coffee tattooed. Pinterest flannel Kickstarter.",
    "Hella organic kombucha. Raw denim deep v. Freegan tousled artisan. Austin gentrify chambray.",
    "Sustainable meditation irony. Retro chillwave typewriter. Vegan leggings beard. Artisan biodiesel beard.",
    "Plaid cliche umami. Normcore YOLO seitan. Chia seed messenger bag. Cardigan sriracha Thundercats.",
    "Disrupt chambray roof party. Taxidermy Tumblr dreamcatcher. Paleo cornhole beard. Irony gastropub craft beer.",
    "Farm-to-table artisan PBR&B. Flexitarian skateboard locavore. Trust fund hoodie irony.",
    "DIY tattooed sustainable. Mixtape aesthetic Wes Anderson. Gluten-free cardigan beard.",
    "Fixie forage typewriter. PBR&B VHS cronut. Flannel single-origin skateboard. Kitsch kale chips Pitchfork.",
    "Succulents tattooed gastropub. Chillwave taxidermy Thundercats. Selvage meditation heirloom.",
    "Bicycle rights tofu normcore. Paleo vinyl kombucha. Hella skateboard artisan. Craft beer irony 8-bit.",
    "Tote bag biodiesel flannel. Organic kale chips ennui. Polaroid DIY fanny pack.Sustainable locavore irony selvage.",
    "Organic sriracha chia tote bag. Artisan plaid beard kale chips. PBR&B narwhal banjo flannel.",
    "Vegan hoodie farm-to-table selfies. Craft beer gluten-free mumblecore. Mustache messenger bag YOLO.",
    "Kombucha Brooklyn pour-over cardigan. Cold-pressed kale chips fixie. Ethical beard biodiesel tote bag.",
    "Retro vinyl dreamcatcher fanny pack. Farm-to-table irony bicycle rights. Pop-up quinoa heirloom skateboard.",
    "Chillwave asymmetrical readymade. Craft beer tattooed tofu irony. Mixtape art party fingerstache.",
    "Locally sourced beard banjo. Vintage typewriter sustainable keffiyeh. Artisanal messenger bag gentrify.",
    "DIY tattooed kale chips vinyl.Vegan skateboard irony chambray. Cray beard fanny pack biodiesel.",
    "Tousled narwhal seitan PBR&B. Chia leggings pour-over twee. Tattooed messenger bag bicycle rights. Retro polaroid beard kombucha.",
    "Plaid tote bag YOLO irony. Farm-to-table chia tattooed shabby chic. Pitchfork typewriter trust fund.",
    "Banjo mustache beard hoodie. Artisan quinoa farm-to-table vinyl. DIY irony craft beer fixie.",
    "Sustainable PBR&B bicycle rights. Vegan narwhal beard tofu. Mustache kale chips locavore.",
    "Tote bag twee dreamcatcher. Gluten-free Brooklyn fanny pack. Retro irony beard messenger bag.",
    "Craft beer vinyl bicycle rights. Locally sourced PBR&B tote bag. Keffiyeh vegan banjo flannel.",
    "Chillwave pour-over beard gentrify. Artisanal tattooed irony kombucha. Mixtape bicycle rights narwhal.",
    "Seitan twee kale chips. Fixie tote bag sustainable. DIY craft beer beard. Retro hoodie typewriter messenger bag.",
    "Chia fingerstache trust fund. Gluten-free beard pour-over banjo. PBR&B narwhal banjo flannel.",
    "Vegan hoodie farm-to-table selfies. Craft beer gluten-free mumblecore. Mustache messenger bag YOLO.",
    "Kombucha Brooklyn pour-over cardigan. Cold-pressed kale chips fixie. Ethical beard biodiesel tote bag.",
    "Retro vinyl dreamcatcher fanny pack. Farm-to-table irony bicycle rights. Pop-up quinoa heirloom skateboard.",
    "Chillwave asymmetrical readymade. Craft beer tattooed tofu irony. Mixtape art party fingerstache.",
    "Locally sourced beard banjo. Vintage typewriter sustainable keffiyeh. Artisanal messenger bag gentrify.",
    "DIY tattooed kale chips vinyl. Vegan skateboard irony chambray. Cray beard fanny pack biodiesel.",
    "Tousled narwhal seitan PBR&B. Chia leggings pour-over twee. Tattooed messenger bag bicycle rights.",
    "Retro polaroid beard kombucha. Plaid tote bag YOLO irony. Farm-to-table chia tattooed shabby chic.",
    "Tattooed messenger bag bicycle rights. Retro polaroid beard kombucha. Plaid tote bag YOLO irony.",
    "Farm-to-table chia tattooed shabby chic. Pitchfork typewriter trust fund. Banjo mustache beard hoodie.",
    "Artisan quinoa farm-to-table vinyl. DIY irony craft beer fixie. Sustainable PBR&B bicycle rights.",
    "Vegan narwhal beard tofu. Mustache kale chips locavore. Tote bag twee dreamcatcher. Gluten-free Brooklyn fanny pack.",
    "Retro irony beard messenger bag. Craft beer vinyl bicycle rights. Locally sourced PBR&B tote bag.",
    "Keffiyeh vegan banjo flannel. Chillwave pour-over beard gentrify. Artisanal tattooed irony kombucha.",
    "Mixtape bicycle rights narwhal. Seitan twee kale chips. Fixie tote bag sustainable. DIY craft beer beard.",
  ]
  },
  { id: 8, 
    name: 'Hockey', 
    sentences: [
    "He's got soft hands around the net. That was a filthy dangle! He's got wheels; he's so fast on the ice.",
    "The goalie stood on his head to make that save. He got sniped top shelf. He dropped the mitts and threw some haymakers.",
    "That was a beauty pass! He's got silky smooth hands. The ref missed a blatant trip there.",
    "The puck took a weird bounce off the boards. He got undressed by a deke. The defenseman pinched in and scored.",
    "He went bar down on that shot. That was a huge slapper from the point. The goalie made a pad save.",
    "He's a grinder, always working hard in the corners. The playmaker set up a beautiful one-timer.",
    "He's a dangler; his stickhandling is incredible. The enforcer dropped the gloves and started a fight.",
    "The goalie made a desperation diving save. The coach benched him for taking a dumb penalty.",
    "He took a clapper from the blue line. The forward backchecked and stole the puck. He got robbed by the goalie's glove save.",
    "The team is in the offensive zone, cycling the puck. He's got a wicked snapshot.",
    "He went five-hole and scored! The defenseman blocked a shot with his body. He's got a cannon of a slapshot.",
    "The team is on the penalty kill. The goalie made a stick save. He got caught cherry-picking at the opponent's blue line.",
    "The forward got a breakaway and scored on a backhand. The ref called a hooking penalty. The goalie made a toe save to keep the game tied.",
    "He's got great hockey IQ; he always makes smart plays. He's a crease crasher; he scores a lot of garbage goals.",
    "The player took a misconduct penalty for arguing with the ref. The goalie made a kick save with his pad.",
    "He got decked with a huge open-ice hit. He sniped it top corner with a wrister.",
    "The forward made a saucer pass over the defenseman's stick. He got stoned by the goalie on a breakaway.",
    "The defenseman laid out a big hit along the boards. The player got called for a high-sticking penalty.",
    "The goalie made a blocker save on a hard shot. He's a pest, always getting under the opponents' skin.",
    "The player took a tripping penalty. He got completely undressed by a toe drag move. The team is on a power play.",
    "He made a diving poke check to break up the play. The goalie made a flashy glove save.",
    "He's a sniper; he has a deadly accurate shot. The defenseman cleared the puck out of the zone.",
    "He sniped that top shelf! The goalie made a sick save. He dangled through the defensemen.",
    "That was a filthy saucer pass. He's got wheels, really fast skater. He dropped the gloves and started a fight.",
    "The game went into overtime. He got a hat trick in the last period. The puck went off the post and in.",
    "The ref called a penalty for hooking. He's a grinder, always working hard. The defenseman blocked a shot with his body.",
    "He got a breakaway and scored. The goalie shut the door, no goals allowed. He went coast to coast for the goal.",
    "The crowd went wild after the big hit. He's got soft hands, great puck handling. The team is in the offensive zone.",
    "He got called for high-sticking. He's a sniper, deadly accurate shot. The game ended in a shootout.",
    "The enforcer laid out a huge hit. He made a great deke to beat the goalie. The game is tied, going into overtime.",
    "He went bar down with the shot. The goalie made a glove save. He's got a rocket of a slap shot.",
    "He got an assist on the goal. The player got ejected for a headshot. The team is on a power play.",
    "He's got silky smooth hands. The goalie made a diving save. He's a playmaker, always setting up goals.",
    "The defenseman pinched in and scored. He got called for tripping. He's got great hockey sense.",
    "The game is tied, going into a shootout. He got boarded and drew a penalty. He's got a heavy shot, hard to stop.",
    "The forward crashed the net and scored. He got called for interference. He's a two-way player, great on offense and defense.",
    "The team is killing a penalty. He got benched for a bad penalty. He's a grinder, always battling in the corners.",
    "The goalie made a pad save. He got called for slashing. He's got good hockey IQ. The team is on a breakaway.",
    "He got cross-checked from behind. He's a goal scorer, always finding the back of the net.",
    "The crowd went wild after the big hit. He's got soft hands, great puck handling. The team is in the offensive zone.",
    "He got called for high-sticking. He's a sniper, deadly accurate shot. The game ended in a shootout.",
    "The enforcer laid out a huge hit. He made a great deke to beat the goalie. The game is tied, going into overtime.",
    "He went bar down with the shot. The goalie made a glove save. He's got a rocket of a slap shot.",
    "He got an assist on the goal. The player got ejected for a headshot. The team is on a power play.",
    "He's got silky smooth hands. The goalie made a diving save. He's a playmaker, always setting up goals.",
    "The defenseman pinched in and scored. He got called for tripping. He's got great hockey sense.",
    "The game is tied, going into a shootout. He got boarded and drew a penalty.He's got good hockey IQ.",
    "He's got a rocket of a slap shot. He got an assist on the goal. The player got ejected for a headshot.",
    "The team is on a power play. He's got silky smooth hands. The goalie made a diving save.",
    "He's a playmaker, always setting up goals. The defenseman pinched in and scored. He got called for tripping.",
    "He's got great hockey sense. The game is tied, going into a shootout. He got boarded and drew a penalty.",
    "He's got a heavy shot, hard to stop. The forward crashed the net and scored.He got called for interference.",
  ]
  },
  { id: 9,
    name: 'Hippie', 
    sentences: [
    "Peace and love, man Make love, not war Groovy vibes Free your mind Turn on, tune in, drop out",
    "Power to the people Love is all you need Spread love like confetti One love, one heart",
    "Love and peace Give peace a chance Imagine all the people All you need is love Make art, not war",
    "Live and let live Flower power Keep on truckin Stay trippy, little hippie Peace, love, and happiness",
    "Find your own truth Love is the answer Make every day Earth Day Embrace the journey",
    "Positive vibes only Live in the moment Spread kindness Be the change Let your soul shine",
    "Keep it groovy Love the earth Peace begins with a smile Live free Chill out, man",
    "Feel the music Make peace, not noise Love, peace, and harmony Infinite love and gratitude",
    "Follow your bliss Stay wild, moon child Dream big, little hippie Be a free spirit Dance like nobody's watching",
    "Choose love over fear Smile, it's contagious Spread positive energy Make the world a better place",
    "Live, love, laugh Find your inner peace Celebrate diversity Peaceful coexistence",
    "Live harmoniously with nature Freedom of expression Peace begins with a smile. Love is the answer, and you know that for sure.",
    "Spread love everywhere you go. Let your soul shine. Make love, not war. The best things in life aren't things.",
    "Freedom is being yourself without permission. Happiness is not a destination, it's a way of life.",
    "Imagine all the people living life in peace. Live simply, dream big, be grateful, give love, laugh lots.",
    "Find beauty in the small things. Love and peace are eternal. Stay wild, moon child.",
    "Keep calm and love everyone. Create your own sunshine. Live in the sunshine, swim in the sea, drink the wild air.",
    "Smile, it's free therapy. Be the change you wish to see in the world. Love is all you need.",
    "Peace, love, and rock 'n' roll. One love, one heart. Life is short, make it sweet.In a world full of hate, be a light.",
    "Embrace the magic of new beginnings. Follow your bliss and the universe will open doors for you.",
    "Find your tribe, love them hard. Let your love be louder than your fear. Dance like nobody's watching.",
    "Good vibes only. Love more, worry less. Be groovy or leave, man. Live, love, and let go.",
    "Plant seeds of love and watch them grow. Free your mind and your soul will follow.",
    "Let the beauty of what you love be what you do. Peace is not something you wish for; it's something you make.",
    "Love is the key to happiness. Happiness is handmade. Dream big, sparkle more, shine bright.",
    "Love the earth as you would love yourself. Life is better when you're laughing.",
    "Give peace a chance. Love yourself first and everything else falls into line. Inhale love, exhale peace.",
    "Make art, spread love. You are never too old to set another goal or dream a new dream.",
    "Let go of your worries nd let the universe guide you. Life is a journey, enjoy the ride.",
    "Find your own truth and live it. Live, love, laugh, let go. Make every day count. Cherish yesterday, dream tomorrow, live today.",
    "Peace begins with a smile. Turn on, tune in, drop out. Make love, not war. In a gentle way, you can shake the world.",
    "Let your freak flag fly. Love is the answer. Imagine all the people lving life in peace.",
    "Be the change you wish to see in the world. Give peace a chance. The best things in life aren't things.",
    "Do more of what makes you happy. Make art, not war. Flower power! Happiness is not a destination; it's a way of life.",
    "Live and let live. Spread love like wildfire. Find yourself and express yourself in your own particular way.",
    "Make love your motto. It's not about what you have, it's about what you give. Love and peace are eternal.",
    "Stay groovy, man. Let the sunshine in. Life is short, make it sweet. Go with the flow.",
    "Take a walk on the wild side. Peace, love, and understanding. Free your mind and the rest will follow.",
    "Follow your heart, it knows the way. Keep on truckin'. The power of love overcomes the love of power.",
    "Spread good vibes everywhere you go. Live for today. Question authority. Drop in, turn on, and drop out.",
    "All you need is love. Dance like nobody's watching. Let your soul shine. Do what you love, love what you do.",
    "Love is a friendship set to music. Be kind to every kind. Make peace, not war.",
    "Keep the Earth clean; it's not Uranus. Groovy, man, groovy! Love is free. Hug a tree.",
    "Life is beautiful, man. Embrace the journey. Don't worry, be happy. Love is all you need.",
    "Live simply and love generously. Love, peace, and rock 'n' roll. Tune in, turn on, drop out.",
    "Live and let live. Spread love like wildfire. Find yourself and express yourself in your own particular way.",
    "Make love your motto. It's not about what you have, it's about what you give.",
    "Love and peace are eternal. Stay groovy, man. Let the sunshine in. Life is short, make it sweet.",
    "Go with the flow. Take a walk on the wild side. Peace, love, and uderstanding.",
    "Free your mind and the rest will follow. Follow your heart, it knows the way. Keep on truckin'.",
  ]
  },
  { id: 10,
    name: 'New Yorker', 
    sentences: [
    "I'm gonna grab a slice and catch the train.",
    "Fuhgeddaboudit! That idea won't fly here.",
    "Hey, watch out for the potholes on this block.",
    "I need my coffee, or I'll be cranky all day.",
    "Let's hit up Times Square and see the lights.",
    "This bagel is the real deal, no imitation stuff.",
    "I can't believe the subway is delayed again.",
    "Get a hot dog from the street vendor, it's a classic.",
    "You got any spare change for a pretzel?",
    "I'm meeting my friends at the bodega later.",
    "The Knicks finally won a game, can you believe it?",
    "I'll take a dirty water dog with mustard, please.",
    "This pizza is legit, just like back in the Bronx.",
    "I need to find a decent slice joint in this neighborhood.",
    "Don't forget to swipe your MetroCard before boarding.",
    "I love walking through Central Park in the fall.",
    "The Empire State Building is a must-see tourist spot.",
    "I can't decide between a bagel or an egg sandwich.",
    "Take a walk along the High Line, it's beautiful.",
    "The hot dog cart is the heart of New York street food.",
    "Let's grab a cold one at the local dive bar.",
    "The Statue of Liberty is an iconic symbol of freedom.",
    "I'll grab a slice to go, I'm in a hurry.",
    "Don't jaywalk, the cops are cracking down on it.",
    "I'm craving some dollar pizza, the ultimate cheap eat.",
    "The Empire State Building offers stunning views.",
    "There's a street fair happening in Chelsea this weekend.",
    "I'm taking the A train up to Harlem for a concert.",
    "I'll have a chopped cheese sandwich, extra mayo.",
    "New York bagels are just on another level.",
    "I'm gonna catch a Broadway show tonight, it's a must-do.",
    "Let's grab a cup of joe at the corner deli.",
    "I'll meet you in front of the Flatiron Building.",
    "You should try a pastrami sandwich from Katz's Deli.",
    "This neighborhood has a real old-school vibe.",
    "I love strolling through Greenwich Village on weekends.",
    "Don't forget your umbrella, it's gonna rain cats and dogs.",
    "I'll have a slice with pepperoni and extra cheese.",
    "This neighborhood is gentrifying pretty quickly.",
    "The hot dog guy on 42nd Street makes the best dogs.",
    "I'm gonna grab a taxi, I don't feel like taking the subway.",
    "Let's take the Staten Island Ferry for a scenic ride.",
    "I'm going to the bodega to grab some snacks for the game.",
    "The street performers in Union Square are always entertaining.",
    "I'll have a knish with mustard, please.",
    "I'm heading to Coney Island for some beach time.",
    "The view from the Top of the Rock is breathtaking.",
    "I need a slice of pizza to cure this hangover.",
    "I'm gonna catch the L train to Williamsburg.",
    "Let's take a walk across the Brooklyn Bridge.",
    "I'm meeting my date at the speakeasy downtown.",
    "The Halal guys have the best chicken and rice platters.",
  ]
  },
  { id: 11,
    name: 'Pirate', 
    sentences: [
    "Avast ye, matey!",
    "Shiver me timbers!",
    "Yo ho ho and a bottle of rum!",
    "Sail ho!",
    "Batten down the hatches!",
    "Ahoy, me hearties!",
    "Blow me down!",
    "Walk the plank!",
    "Dead men tell no tales.",
    "Thar she blows!",
    "Aye, aye, captain!",
    "Hoist the Jolly Roger!",
    "Scurvy dog!",
    "X marks the spot!",
    "Land ho!",
    "Aye, me bucko!",
    "Prepare to be boarded!",
    "Davy Jones' locker awaits!",
    "A pirate's life for me!",
    "Arr, me matey!",
    "Savvy?",
    "Pieces of eight!",
    "Cap'n says so!",
    "Thar be treasure!",
    "Avast, ye landlubber!",
    "Sink me!",
    "By Blackbeard's beard!",
    "To the depths of the sea!",
    "Thar be rough waters ahead!",
    "Aye, the wind be at our backs!",
    "Set sail for adventure!",
    "No prey, no pay!",
    "Curses upon ye!",
    "A pirate never reveals his secrets.",
    "All hands on deck!",
    "Splice the mainbrace!",
    "Aye, the sea be a cruel mistress.",
    "A gold doubloon for your thoughts!",
    "Raise the anchor!",
    "Avast, me hearties, for a jolly good time!",
    "May your compass always point true!",
    "Beware the Kraken!",
    "Fair winds and following seas!",
    "Aye, the pirate's life be the only life!",
    "Avast, ye scurvy landlubbers!",
    "Aye, the rum be gone!",
    "Take what ye can, give nothin' back!",
    "In the heart of a pirate beats the soul of a free man!",
    "Aye, the open sea calls to me!",
    "Thar be adventure on the horizon!",
    "A pirate's treasure is never far away!",
    "Yo ho ho! We sail for glory!"
  ]
  },
  { id: 12,
    name: 'Rasta', 
    sentences: 
    [
    "One Love",
    "Jah Bless",
    "Irie vibes",
    "Give thanks",
    "Babylon system",
    "Inity",
    "Jah Rastafari",
    "Positive vibrations",
    "Selassie I",
    "Upfull",
    "Herb is the healing",
    "Livity",
    "Jah guide",
    "Jah live",
    "Jah know",
    "Righteousness",
    "Blessed love",
    "Natty dread",
    "Roots and culture",
    "Overstanding",
    "I and I",
    "Bun Babylon",
    "Jah Jah",
    "Rasta Far I",
    "Freedom fighter",
    "Zion train",
    "Praise Jah",
    "Jah army",
    "Jah works",
    "Jah children",
    "Rasta man",
    "Rasta love",
    "Jah creation",
    "Bless up",
    "Higher heights",
    "Mount Zion",
    "Peace and love",
    "Chant down Babylon",
    "Rasta unity",
    "One heart",
    "Hail Jah",
    "Ras Tafari",
    "Consciousness",
    "Spiritual journey",
    "Lion of Judah",
    "Divine love",
    "Equal rights",
    "Zion gate",
    "Trod on",
    "Rasta wisdom",
    "Iyah"
  ]
  },
  { id: 13,
    name: 'Surfer', 
    sentences: [
    "Dude, that wave was gnarly!",
    "Hang ten, bro!",
    "I caught a sick barrel!",
    "The surf's firing today!",
    "Time to wax up and hit the lineup!",
    "Stoked to be shredding some waves!",
    "Cowabunga, dudes!",
    "Tubular ride, man!",
    "Radical cutback on that last wave!",
    "Dropping in on the left, watch out!",
    "Sick bottom turn, bro!",
    "Let's paddle out and catch some bombs!",
    "That wave had some serious juice!",
    "I'm going switch-stance on this one!",
    "The sets are rolling in, epic conditions!",
    "Caught some tasty little peelers out there!",
    "The ocean is my happy place!",
    "I'm going for an air on the next wave!",
    "Cowabunga, baby!",
    "That was a sick floater, dude!",
    "The surf gods are smiling upon us today!",
    "Whoa, did you see that aerial maneuver?!",
    "Just hanging loose and enjoying the ride!",
    "The offshore winds are perfect for surfing!",
    "Dropping in deep and getting barreled!",
    "Time to paddle back out and catch another!",
    "Aloha, my wave-riding brethren!",
    "I'm getting pitted in the green room!",
    "Let's shred this peak together!",
    "Waves for days, life is good!",
    "I'm carving up the face of this wave!",
    "Surfing is my ultimate therapy!",
    "That wave was firing like a freight train!",
    "Dawn patrol session, the best way to start the day!",
    "Epic sunset sesh, can't beat these colors!",
    "Paddle faster, the set is coming!",
    "Just hanging ten and enjoying the ride!",
    "The surf forecast is looking epic!",
    "This wave is a real screamer!",
    "I'm getting pitted, no worries!",
    "Time to bust out some sick tricks!",
    "The ocean is calling, gotta answer!",
    "That wave had a sick wall to it!",
    "I'm in the zone, catching everything in sight!",
    "Let's go for a surfari and explore new breaks!",
    "Surf's up, let's get radical!",
    "Slashing through the lip, feeling the flow!",
    "I'm chasing that endless summer vibe!",
    "Soul surfing is where it's at!",
    "This wave is reeling like a dream!",
    "The sea is my playground, always stoked!",
    "Hooting and hollering for my fellow surfers!"
  ]
  },
  { id: 14,
    name: 'Stoner', 
    sentences: 
    [
    "Dude, pass the blunt.",
    "I'm so baked right now.",
    "Let's get high and watch movies.",
    "Whoa, everything is so trippy.",
    "Do you have any munchies?",
    "I'm floating on cloud nine.",
    "This weed is top-notch.",
    "I can't feel my face.",
    "The universe is so vast, man.",
    "Let's take another hit.",
    "Time is a social construct, man.",
    "I'm one with the universe.",
    "Have you ever really looked at your hand?",
    "Life is like, so profound, you know?",
    "Nature is so beautiful when you're high.",
    "I forgot what we were talking about.",
    "I need a break, my brain is fried.",
    "This music sounds incredible right now.",
    "Let's go on a cosmic adventure.",
    "My mind is expanding with every toke.",
    "Did we just solve the world's problems?",
    "I'm in a state of bliss.",
    "I can't stop giggling, man.",
    "Pass the chips, I have the munchies.",
    "I'm too stoned to drive, let's order in.",
    "What if colors had flavors?",
    "Time is moving so slow, it's insane.",
    "Let's just chill and enjoy the high.",
    "My thoughts are like a kaleidoscope.",
    "I feel so connected to everything.",
    "I think I just had an epiphany, man.",
    "This strain is out of this world.",
    "I could stare at this lava lamp forever.",
    "The meaning of life is 42... or is it?",
    "I'm lost in the depths of my own mind.",
    "I can taste colors, man.",
    "Let's go on a nature walk and get lost.",
    "I'm in a parallel universe right now.",
    "I'm getting lost in this couch.",
    "This is some mind-altering stuff.",
    "Do you ever wonder if the stars get high?",
    "Time is an illusion, man.",
    "I'm so relaxed, I could melt into the floor.",
    "Did I just hear the plants talking?",
    "What if our dreams are actually reality?",
    "I feel like I'm swimming through thoughts.",
    "I'm on a higher plane of existence.",
    "I can taste the rainbow, man.",
    "Everything is groovy, man.",
    "Let's roll another joint and ponder the mysteries of the universe.",
    "I can see the energy flowing through everything.",
    "My mind is a swirling vortex of ideas.",
    "This weed is like a magic carpet ride."
  ]
  },
  { id: 15,
    name: 'Star Wars',
    sentences:
    [
    "May the Force be with you.",
    "I've got a bad feeling about this.",
    "Do. Or do not. There is no try.",
    "I find your lack of faith disturbing.",
    "It's a trap!",
    "The Force will be with you, always.",
    "I love you. I know.",
    "You were the chosen one!",
    "The Force is strong with this one.",
    "In my experience, there is no such thing as luck.",
    "It's not my fault.",
    "I am your father.",
    "I'm just a simple man trying to make my way in the universe.",
    "Help me, Obi-Wan Kenobi. You're my only hope.",
    "The dark side of the Force is a pathway to many abilities some consider to be unnatural.",
    "I've got a bad feeling about this.",
    "I will finish what you started.",
    "It's the ship that made the Kessel Run in less than twelve parsecs.",
    "Aren't you a little short for a stormtrooper?",
    "Stay on target.",
    "I'll never join you!",
    "You were right about me. Tell your sister... you were right.",
    "I am altering the deal. Pray I don't alter it any further.",
    "You were the chosen one! It was said that you would destroy the Sith, not join them!",
    "I've got a bad feeling about this.",
    "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.",
    "Why, you stuck-up, half-witted, scruffy-looking nerf herder!",
    "I'm one with the Force. The Force is with me.",
    "I find your lack of faith disturbing.",
    "It's a trap!",
    "I've got a bad feeling about this.",
    "I will not be the last Jedi.",
    "Great shot, kid, that was one in a million!",
    "The Force will be with you, always.",
    "I love you. I know.",
    "I've got a bad feeling about this.",
    "You were the chosen one!",
    "The Force is strong with this one.",
    "It's not my fault.",
    "I am your father.",
    "I'm just a simple man trying to make my way in the universe.",
    "Help me, Obi-Wan Kenobi. You're my only hope.",
    "I've got a bad feeling about this.",
    "I will finish what you started.",
    "It's the ship that made the Kessel Run in less than twelve parsecs.",
    "Aren't you a little short for a stormtrooper?",
    "Stay on target.",
    "I'll never join you!",
    "You were right about me. Tell your sister... you were right.",
    "I am altering the deal. Pray I don't alter it any further.",
    "You were the chosen one! It was said that you would destroy the Sith, not join them!",
    "I've got a bad feeling about this."
  ]
  },
  { id: 16,
    name: 'Geek',
    sentences: [
    "May the force be with you.",
    "There's no place like 127.0.0.1",
    "I am root.",
    "It's not a bug, it's a feature.",
    "404: Brain not found.",
    "I speak fluent binary.",
    "Talk nerdy to me.",
    "Geek is the new sexy.",
    "There are only 10 types of people in the world: those who understand binary and those who don't.",
    "sudo make me a sandwich",
    "I void warranties.",
    "Keep calm and code on.",
    "I'm not lazy, I'm on energy-saving mode.",
    "Ctrl + Alt + Del is my cardio.",
    "Error 404: Costume not found.",
    "I see dead pixels.",
    "No, I will not fix your computer.",
    "I find your lack of faith disturbing.",
    "In code we trust.",
    "I'm not a nerd, I'm just intellectually curious.",
    "Code blooded.",
    "I'd explain it to you, but your brain would explode.",
    "I'm silently correcting your grammar.",
    "I'm not antisocial, I'm just not user-friendly.",
    "These aren't the droids you're looking for.",
    "I code, therefore I am.",
    "I came, I saw, I conquered... the code.",
    "I'm fluent in three languages: English, Sarcasm, and Binary.",
    "I'm not a geek, I'm a level 12 Paladin.",
    "Error 404: Coffee not found.",
    "My other car is the Millennium Falcon.",
    "Keep calm and hack the planet.",
    "I'm a Ctrl freak.",
    "I turn coffee into code.",
    "Error: Keyboard not found. Press F1 to continue.",
    "I'm not anti-social; I'm just not user-friendly.",
    "There's no place like ~",
    "I'm not weird, I'm just limited edition.",
    "I'm a Mac / I'm a PC",
    "There's no kill like overkill.",
    "Code it like you mean it.",
    "I have too many tabs open in my brain.",
    "Geek by day, gamer by night.",
    "I have a great Ctrl over my life.",
    "There's no app for that.",
    "I put the 'fun' in functional.",
    "I speak Klingon.",
    "There are only 10 types of people: those who understand hexadecimal and 15 others.",
    "I'm not lazy, I'm just highly efficient.",
    "I find your lack of coding skills disturbing.",
    "I'm a syntax error in the system of life.",
    "I break keyboards, not hearts.",
    "I'm a pixel pusher.",
    "Talk nerdy to me, baby!"
    ] 
  }
]

export default ipsums