const ipsums = [
  { id: 1,
    name: 'Bob Ross',
    sentences: 
    [
      "Happy little trees.",
      "We don't make mistakes, just happy little accidents.",
      "There's nothing wrong with having a tree as a friend.",
      "Just beat the devil out of it.",
      "Let's give him a friend too. Everybody needs a friend.",
      "There's an artist hidden at the bottom of every single one of us.",
      "The only thing worse than yellow snow is green snow.",
      "Clouds are very, very free.",
      "In painting, you have unlimited power. You have the ability to move mountains.",
      "Believe that you can do it 'cause you can do it.",
      "You need the dark in order to show the light.",
      "You can do anything you want to do. This is your world.",
      "Talent is a pursued interest. Anything that you're willing to practice, you can do.",
      "I believe talent is just a pursued interest.",
      "The secret to doing anything is believing that you can do it.",
      "We don't really know where this goes - and I'm not sure we really care.",
      "There are no mistakes, only happy accidents.",
      "We want happy paintings. Happy paintings. If you want sad things, watch the news.",
      "You can have anything you want in the world - once you help everyone around you succeed.",
      "This is happy place; little squirrels live here and play.",
      "Let's make a nice big leafy tree.",
      "There's nothing wrong with having a tree as a friend.",
      "You can put as many or as few as you want in your world.",
      "The more we do this - the more it will do good things to our heart.",
      "We don't laugh because we feel good, we feel good because we laugh.",
      "We don't make mistakes, we just have happy accidents.",
      "This is your world. You're the creator. Find freedom on this canvas.",
      "Just take out whatever you don't want. It'll change your entire perspective.",
      "We might as well make some Almighty mountains today as well, what the heck.",
      "This is the fun part. Just beat the devil out of it.",
      "You can put as many or as few as you want in your world.",
      "Every highlight needs its own personal shadow.",
      "Decide where your little footy hills live.",
      "We'll throw some happy little limbs on this tree.",
      "There's not a thing in the world wrong with washing your brush.",
      "Don't forget to tell these special people in your life just how special they are to you.",
      "You need the dark in order to show the light.",
      "You can create anything that makes you happy.",
      "You're meant to have fun in life.",
      "Let's build some happy little clouds up here.",
      "A tree needs to be your friend if you're going to paint him.",
      "There is no right or wrong - as long as it makes you happy and doesn't hurt anyone.",
      "Talk to the tree, make friends with it.",
      "Get away from those little Christmas tree things we used to make in school.",
      "Talent is a pursued interest. Anything that you're willing to practice, you can do.",
      "It's a super day, so why not make a beautiful sky?",
      "Let's do something nice and easy now.",
      "Remember how free clouds are. They just lay around in the sky all day long.",
      "Just let these leaves jump off the brush.",
      "Just relax and let it flow. That easy.",
      "You can create beautiful things - but you have to see them in your mind first.",
      "Look around. Look at what we have. Beauty is everywhere—you only have to look to see it.",
      "Just go out and talk to a tree. Make friends with it.",
      "Trees get lonely too, so we'll give him a little friend.",
      "The more we do this, the more it will do good things to our heart.",
      "We'll just throw a few little lines in here and there.",
      "We don't really know where this goes - and I'm not sure we really care.",
      "Don't be afraid to make these big decisions. Once you start, they sort of just make themselves.",
      "In nature, dead trees are just as normal as live trees.",
      "Only God can make a tree - but you can paint one.",
      "I think there's an artist hidden at the bottom of every single one of us.",
      "All you need to paint is a few tools, a little instruction, and a vision in your mind.",
      "Water's like me. It's lazy. Boy, it always looks for the easiest way to do things.",
      "The only prerequisite is that it makes you happy. If it makes you happy then it's good.",
      "I really believe that if you practice enough you could paint the 'Mona Lisa' with a two-inch brush.",
      "This is a happy place, little squirrels live here and play.",
      "Everybody needs a friend.",
      "You can have anything you want in the world - once you help everyone around you succeed.",
      "We have no limits to our world. We're only limited by our imagination.",
      "We don't make mistakes, we have happy accidents.",
      "You need to have a little sadness once in a while so you know when the good times come.",
      "From all of us here, I want to wish you happy painting...and God bless, my friend.",
      "This is your creation - and it's just as unique and special as you are.",
      "I think each of us, sometime in our life, has wanted to paint a picture.",
      "Anything that you believe you can do strong enough, you can do. Anything. As long as you believe.",
      "And maybe, maybe, there's a happy little bush that lives right there.",
      "If you don't think you can do it - you're not going to do it. If you really want to do it, you can do it.",
      "If I paint something, I don't want to have to explain what it is.",
      "All you need to paint is a few tools, a little instruction, and a vision in your mind.",
      "People might look at you a bit funny, but it's okay. Artists are allowed to be a bit different.",
      "Anything that works for you is okay.",
      "In your imagination you can go anywhere you want.",
      "In life you need colors.",
      "Life is too short to be alone, too precious. Share it with a friend.",
      "Only God can make a tree - but you can paint one.",
      "The least little bit can do so much.",
      "Be so very light. Be a gentle whisper.",
      "Just make a decision and let it go.",
      "Just go out and talk to a tree. Make friends with it.",
      "From all of us here I want to wish you happy painting and God bless my friend.",
      "You need the dark in order to show the light.",
      "Laughter is a necessity in life. It's a gift, a precious gift.",
      "We don't really know where this goes - and I'm not sure we really care.",
      "Water's like me. It's lazy. Boy, it always looks for the easiest way to do things.",
      "We artists are a different breed of people. We're a happy bunch.",
      "I like to beat the brush.",
      "I'm gonna start with a little Alizarin crimson and a touch of Prussian blue.",
      "The shadows are just like the highlights, but we're putting them in reverse.",
      "You know me, I gotta put in a big tree.",
      "Let's put some happy little clouds in our world.",
      "We don't really know where this goes - and I'm not sure we really care.",
      "And maybe, maybe, there's a happy little bush that lives right there.",
      "If you don't think you can do it - you're not going to do it. If you really want to do it, you can do it.",
      "This is your world. You're the creator. Find freedom on this canvas.",
      "The only thing worse than yellow snow is green snow.",
      "We might as well make some Almighty mountains today as well, what the heck.",
      "I'm gonna start with a little Alizarin crimson and a touch of Prussian blue.",
      "Let's put some happy little clouds in our world."
    ]
  },
  { id: 2,
    name: 'Boston', 
    sentences: 
    [
      "Wicked smaht",
      "Pahk the cah in Hahvahd Yahd",
      "Bang a U-ey",
      "Wicked pissah",
      "Chowdah-head",
      "Pissed as a pahty",
      "Gawker's block",
      "Sweata weatha",
      "Packie run",
      "Bubbler",
      "Jiminy Christmas",
      "Cape Cod curtain",
      "No-see-ums",
      "Bust my buttons",
      "Baked beans for breakfast",
      "Slap some scrod on the grill",
      "It's a bear of a traffic",
      "Dunkies run",
      "Tonic for soda",
      "Scrod it up",
      "Wear your bean boots",
      "Quinzee",
      "Triple-deckah",
      "Bumpah to bumpah",
      "Rippah",
      "Southie",
      "Sweatin' like a sinner in church",
      "Jimmies on your ice cream",
      "The Pike",
      "Slumbah",
      "Stahm's a-brewin'",
      "Get a lobster roll at the shack",
      "Standin' at the packie",
      "Wearin' ya wicked warm coat",
      "Catchin' the T",
      "Droppin' the R's",
      "Got a real wicked Boston accent",
      "Friggin' freezin'",
      "Winnah winnah, chicken dinnah",
      "Patriots game at Gillette",
      "Hittin' the Habah",
      "Rolling through the Common",
      "Scrubbin' the deck",
      "Bostonski",
      "Tourists on the Duck Boat",
      "Fenway franks",
      "Shovelin' snow off the cah",
      "Wearin' the green on St. Paddy's",
      "Sullivan Square",
      "Pike traffic, what a shockah",
      "Lobstah trap decor",
      "Fishin' off the Cape",
      "Brahmin accent",
      "Savin' up for a Cape house",
      "Sailin' in the harbor",
      "Wearin' your wicked old Bruins jersey",
      "Pops on the Esplanade",
      "Salem in October",
      "Hittin' up Newbury Street",
      "Gettin' steamahs at the clam shack",
      "Goin' to Revere Beach",
      "Goin' down the Cape",
      "Takin' a swan boat ride",
      "Tourin' the Freedom Trail",
      "Wearin' your Pats cap",
      "Sippin' on Dunks",
      "Sailin' the Charles River",
      "Havin' a chowdah cook-off",
      "Hikin' in the Blue Hills",
      "Wearin' ya Southie pride",
      "Headin' to the Cape Cod Baseball League",
      "Watchin' the Boston Marathon",
      "Chillin' at Castle Island",
      "Cape traffic, absolute nightmah",
      "Wicked hahd workout",
      "Loadin' up on lobstah bisque",
      "Bumpin' into a Kennedy",
      "Chowdah, clam cakes, and clam chowdah",
      "Jammin' at a Fenway concert",
      "Walkin' the Charles with a frapp",
      "Swingin' by Cheers on Beacon Hill",
      "Watchin' planes at Logan",
      "Wearin' the Celtic green",
      "Rollerbladin' on the Esplanade",
      "Beantown hustle",
      "Wicked good time",
      "Sippin' Sam Adams in Jamaica Plain",
      "Wearin' a Red Sox cap to a Yankees game",
      "Drivin' the cah to the Cape",
      "Pahkin' at Fenway",
      "Reenactin' the Tea Party",
      "Goin' whale watchin' in Gloucester",
      "Havin' a wicked pissa clambake",
      "Sippin' a coffee at the Boston Common",
      "Stoppin' at Sullivan's for fried clams",
      "Picnic at the Public Garden",
      "Wearin' your chowdah-stained sweatshirt",
      "Wicked hahd lobstah trap pullin'",
      "Rollin' down to Plymouth Rock",
      "Wicked sunny day in the North End",
      "Rockport's beauty",
      "Jammin' at a live show in Cambridge",
      "Surfin' at Cape Cod",
      "Tourin' Fenway Park",
      "Runnin' the Charles River Esplanade",
    ]
  }, 
  { id: 3,
    name: 'Mr Rogers', 
    sentences: 
    [
      "Look for the helpers.",
      "You are special just the way you are.",
      "I like you just the way you are.",
      "It's a beautiful day in the neighborhood.",
      "Won't you be my neighbor?",
      "There's only one person in the world like you.",
      "It's okay to be curious about things.",
      "I'm proud of you for trying.",
      "You make each day a special day.",
      "Sometimes the best thing we can do is just listen.",
      "I'm grateful to have you as my friend.",
      "It's good to talk about things.",
      "Discovering the truth about ourselves is a lifetime's work.",
      "You've made this day a special day by just your being you.",
      "You are growing every day.",
      "You're never too old to learn something new.",
      "You are the only person who can be you.",
      "The world needs a person like you.",
      "You can make the ordinary extraordinary.",
      "You have many gifts.",
      "You are someone who is loved.",
      "You are unique, and so is every person you meet.",
      "It's not always easy, but you can learn to make good choices.",
      "I'm glad you're my friend.",
      "You've made today a special day by just being you.",
      "There's no one else in the world quite like you.",
      "You have so many ways to be a friend.",
      "You're growing every day.",
      "There's only one you in the world.",
      "You've made this day a special day, just by being you.",
      "The more you wonder, the more you understand.",
      "You're always growing and changing.",
      "You are my friend.",
      "You're capable of great things.",
      "You're important to me.",
      "It's the inside that counts.",
      "I'm glad you're you.",
      "It's good to talk about things that scare us.",
      "You have a way of being a good neighbor.",
      "I'm glad we're friends.",
      "You're a very special person.",
      "You are the only person who can be you.",
      "You make my day special.",
      "You're growing in wonderful ways.",
      "You're a good listener.",
      "It's good to talk about things that scare us.",
      "You make every day a special day.",
      "You're a great friend.",
      "You are my friend, and I like you.",
      "I like you just the way you are.",
      "You're someone who's a very good friend of mine.",
      "You've made today a special day, by just being you.",
      "You're growing every day.",
      "You are growing in important ways.",
      "There's no one in the world quite like you.",
      "You're a very important person in my life.",
      "I'm glad you're you.",
      "You're important to me.",
      "You make my day special.",
      "You're a great friend.",
      "You're the only person who can be you.",
      "It's you I like.",
      "It's good to be curious about things.",
      "You have a special way of being a friend.",
      "You're growing in wonderful ways.",
      "You've made today a special day just by being you.",
      "You're a good friend.",
      "You make every day a special day.",
      "You're a good friend to me.",
      "It's not always easy, but you can make good choices.",
      "You make every day a special day just by being you.",
      "You're a good friend.",
      "You are my friend, and I like you.",
      "You make my day special.",
      "You're someone who's a very good friend of mine.",
      "You're a very important person in my life.",
      "You're someone I like very much.",
      "You're a great friend to me.",
      "You are special, and I like you just the way you are.",
      "You're growing in important ways.",
      "You're a good listener.",
      "You're important to me.",
      "You have a special way of being a friend.",
      "You're the only person who can be you.",
      "It's you I like.",
      "It's good to be curious about things.",
      "You have a way of being a good neighbor.",
      "You're someone who's a very good friend of mine.",
      "You are special, and I like you just the way you are.",
      "You make my day special.",
      "You're growing in important ways.",
      "You're important to me.",
      "You have a special way of being a friend.",
      "You're the only person who can be you.",
      "It's you I like.",
      "It's good to be curious about things.",
      "You have a way of being a good neighbor.",  
    ]
  },
  { id: 4,
    name: 'Cowboy', 
    sentences: [
      "Happy trails to you, partner.",
      "Yeehaw! Let's ride into the sunset.",
      "Saddle up and let's hit the trail.",
      "Keep your spurs sharp and your pistol loaded.",
      "A cowboy's word is his bond.",
      "Don't squat with your spurs on.",
      "Sometimes you eat the dust, sometimes the dust eats you.",
      "Life's a rodeo, and sometimes you get thrown.",
      "Never approach a bull from the front, a horse from the rear, or a fool from any direction.",
      "Ride fast, shoot straight, and never back down.",
      "If you're gonna talk the talk, you better walk the walk.",
      "A true cowboy ain't afraid to get a little dirt on his boots.",
      "Speak your mind, but ride a fast horse.",
      "The only way to learn to ride a horse is to get on and fall off.",
      "Cowboys don't complain, they just ride harder.",
      "Good judgment comes from experience, and a lot of that comes from bad judgment.",
      "Trust in your horse, but keep your gun close.",
      "Don't let your yearnings get ahead of your earnings.",
      "Never miss a good chance to shut up.",
      "Keep your chin up and your heart open.",
      "When you're in a hole, the first thing to do is stop digging.",
      "There's no such thing as bad weather, just bad clothing.",
      "Life's too short to ride slow horses.",
      "The quickest way to double your money is to fold it in half and put it back in your pocket.",
      "Stay true to who you are, even when the going gets tough.",
      "Ride as if the devil were chasing you.",
      "A cowboy is a man with guts and a horse.",
      "The only guarantee in life is death and taxes.",
      "Luck is what happens when preparation meets opportunity.",
      "Don't let yesterday use up too much of today.",
      "A good cowboy never takes more than his fair share.",
      "Sometimes you have to let go of the reins and trust the horse.",
      "If you find yourself in a hole, the first thing to do is stop digging.",
      "When you're thrown off a horse, get right back in the saddle.",
      "Don't count your chickens before they're hatched.",
      "Let your actions speak louder than your words.",
      "Never wrestle with a pig. You both get dirty, but the pig likes it.",
      "A cowgirl's heart is as wild as her horse.",
      "A true cowboy respects the land and the animals.",
      "The best way to get ahead is to do what needs to be done.",
      "Ride like the wind and never look back.",
      "It's not the years in your life that count, it's the life in your years.",
      "Don't let fear hold you back from your dreams.",
      "A cowboy's heart is in the right place, even if his boots aren't.",
      "The only bad workout is the one that didn't happen.",
      "Take risks, but always have a way out.",
      "The only time to look down on someone is when you're helping them up.",
      "Treat your horse with kindness and he'll carry you through anything.",
      "Don't just talk the talk, ride the ride.",
      "You can't unsay a cruel word.",
      "In life, as in rodeo, it's not how hard you hit, but how well you can take a hit.",
      "Measure twice, cut once, and never look back.",
      "Cowboys don't run, they ride.",
      "Believe in yourself, even when others don't.",
      "Always saddle your own horse.",
      "A good friend is like a four-leaf clover: hard to find and lucky to have.",
      "There's no such thing as a free ride.",
      "When in doubt, let your horse do the thinking.",
      "You can't rope and tie what you can't catch.",
      "Ride tall in the saddle and never back down from a challenge.",
      "Don't let success go to your head or failure to your heart.",
      "A cowboy's loyalty is as strong as his horse's stride.",
      "The only thing you get from looking back is a sore neck.",
      "When you're thrown off a horse, get back on and ride.",
      "A true cowboy knows the difference between right and almost right.",
      "Treat all living beings with kindness and respect.",
      "There's no such thing as a free lunch.",
      "The best view comes after the hardest climb.",
      "A cowboy's legacy is written in the stories he leaves behind.",
      "Chase your dreams like they stole something from you.",
      "A good horse makes short miles.",
      "It's better to ask forgiveness than permission.",
      "The road to success is often dirtier than the trail.",
      "Ride hard, live free, and never look back.",
      "Don't let anyone fence in your dreams.",
      "A true cowboy knows that patience is a virtue.",
      "A cowboy's handshake is his word.",
      "Live your life so that your epitaph tells a story worth reading.",
      "Keep your eye on the horizon, but never forget where you came from.",
      "A cowboy's courage isn't measured by his size, but by his heart.",
      "Ride for the brand and everything else will fall into place.",
      "Don't let the storms of life get you down; learn to dance in the rain.",
      "A cowboy's grit is stronger than the toughest leather.",
      "When the going gets tough, the tough get riding.",
      "A true cowboy treats ladies with respect and horses with kindness.",
      "There's no shame in walking away from a fight you can't win.",
      "The best sermons are lived, not preached.",
      "A cowboy's hat is a symbol of his pride and his shade.",
      "Don't be afraid to blaze your own trail.",
      "A wise cowboy knows when to hold 'em and when to fold 'em.",
      "Keep your words soft and sweet, just in case you have to eat them.",
      "A true cowboy's legacy lives on in the stories told around the campfire.",
      "When you fall off a horse, you get back on and ride even faster.",
      "Don't let fear of striking out keep you from stepping up to the plate.",
      "A cowboy's heart is big enough to hold all of his dreams.",
      "The best riders are the ones who have fallen the most times.",
      "Ride the river of life wherever it takes you.",
      "A true cowboy knows that strength is found in humility.",
      "Don't wait for your ship to come in; swim out and meet it.",
      "A cowboy's integrity is worth more than gold.",
      "Ride with honor, or don't ride at all.",
      "The trail may be rough, but the journey is worth it.",
      "A true cowboy's loyalty is unwavering, just like the North Star.",
      "Don't be afraid to let your light shine, even in the darkest of times.",
      "A cowboy's dreams are as endless as the prairie sky.",
      "Ride through life like there's no tomorrow.",
      "A true cowboy knows that love is as wild as a bucking bronco.",
      "Don't let anyone rein in your spirit.",
      "The best way to predict the future is to create it.",
      "A cowboy's legacy lives on in the stories he leaves behind.",
      "Ride the highs and the lows, for they make up the rhythm of life.",
      "A true cowboy's worth is measured by the hearts he's touched.",
      "Don't be afraid to get a little dirt under your fingernails.",
      "A cowboy's spirit is as untamed as the wind on the open range.",
      "Let your heart be your guide, and your horse be your friend.",
      "A true cowboy's story is written with every hoofprint he leaves.",
      "Don't let the fences of life confine your dreams.",
      "Ride through the storms and you'll find the rainbows.",
      "A cowboy's journey is never done; it's just the end of one trail and the start of another.",
    ]
  },
  { id: 5,
    name: 'Gamer', 
    sentences : [
      "GGWP (Good Game, Well Played)",
      "Noob here!",
      "Lag is my worst enemy.",
      "Just one more turn...",
      "RNGesus, be kind!",
      "I need more mana!",
      "Pew pew pew!",
      "I'm in it for the loot.",
      "Can't talk, gaming.",
      "Aim for the head!",
      "Time to respawn.",
      "I smell a camper.",
      "I see a red barrel, I shoot.",
      "Stay frosty.",
      "360 no scope!",
      "Teamwork makes the dream work.",
      "The grind never stops.",
      "I live for critical hits.",
      "May your frame rates be high and your temperatures low.",
      "I'm a bot slayer.",
      "My K/D ratio is sacred.",
      "Brb, raiding a dungeon.",
      "I'm on a winning streak!",
      "This game is my life.",
      "Praise the sun!",
      "It's all about strategy.",
      "I need healing!",
      "Time to unleash my ultimate.",
      "Can't get enough of that loot.",
      "Just keep respawning.",
      "No scope, no hope.",
      "Gaming is not a hobby; it's a lifestyle.",
      "Ready player one.",
      "I'm a loot hoarder.",
      "My reflexes are unmatched.",
      "I play, I conquer.",
      "I eat, sleep, and game.",
      "Gotta catch 'em all!",
      "I play with a controller, not a keyboard.",
      "In the zone.",
      "My setup is lit.",
      "I don't rage quit, I tactical retreat.",
      "Victory royale!",
      "Game on!",
      "Press F to pay respects.",
      "I'm on fire!",
      "Gaming > Reality.",
      "Headshot master.",
      "FPS is life.",
      "I speak fluent gamer.",
      "Stay in cover!",
      "I frag out.",
      "Born to game, forced to work.",
      "I identify as a gamer.",
      "My mouse is an extension of my arm.",
      "No lag, no problems.",
      "Console or PC, we're all gamers.",
      "I'm the ultimate boss slayer.",
      "A gamer never dies; they respawn.",
      "I'm in the danger zone.",
      "Level up!",
      "I dream in pixels.",
      "I'm not addicted; I'm dedicated.",
      "The gaming chair is my throne.",
      "I'm the hero this game deserves.",
      "All I need is caffeine and games.",
      "Skill > Luck.",
      "I play to win.",
      "I'm the one-man army.",
      "Low health, high stakes.",
      "I'm a gaming sensation.",
      "Slay all day.",
      "Respawn, reload, repeat.",
      "Just let me finish this level.",
      "I'm the last hope for humanity.",
      "I'm a pixel warrior.",
      "Time to frag and bag.",
      "Stay sharp, stay alive.",
      "I'm the controller of my fate.",
      "Gaming is my cardio.",
      "I'm the MVP.",
      "Keep calm and game on.",
      "Skillshot master.",
      "I'm the king/queen of the leaderboard.",
      "I'm a virtual legend.",
      "Never underestimate a gamer.",
      "I'm a raid leader.",
      "I'm the guardian of my virtual realm.",
      "Can't stop, won't stop gaming.",
      "I play, therefore I am.",
      "Stay alive, stay victorious.",
      "I'm the captain of my gaming team.",
      "I'm a joystick jockey.",
      "Gaming is my therapy.",
      "I'm the ruler of my pixelated kingdom.",
      "May your graphics be sharp and your FPS high.",
      "I'm a loot ninja.",
      "No hacks, just skills.",
      "I'm a controller commander.",
      "Game over is not in my vocabulary.",
      "Virtual reality is my second home.",
      "I'm the voice chat warrior.",
      "I'm a digital gladiator.",
    ]
  },
  {id: 6,
    name: 'Harry Potter', 
    sentences: [
      "I solemnly swear that I am up to no good.",
      "Yer a wizard, Harry.",
      "It does not do to dwell on dreams and forget to live.",
      "After all this time? Always.",
      "Turn to page 394.",
      "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
      "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
      "Nitwit! Blubber! Oddment! Tweak!",
      "Not my daughter, you bitch!",
      "Wit beyond measure is man's greatest treasure.",
      "Dobby is a free elf.",
      "I am what I am, an' I'm not ashamed.",
      "The ones that love us never really leave us.",
      "Just because you have the emotional range of a teaspoon doesn't mean we all have.",
      "The scar had not pained Harry for nineteen years. All was well.",
      "It is our choices, Harry, that show what we truly are, far more than our abilities.",
      "I am a wizard, not a baboon brandishing a stick.",
      "The world isn’t split into good people and Death Eaters.",
      "We could all have been killed — or worse, expelled.",
      "I don't go looking for trouble. Trouble usually finds me.",
      "It’s the unknown we fear when we look upon death and darkness, nothing more.",
      "Do not pity the dead, Harry. Pity the living, and above all, those who live without love.",
      "Do not let your past dictate who you are, but let it be part of who you will become.",
      "Happiness can be found in the darkest of times, if one only remembers to turn on the light.",
      "Time will not slow down when something unpleasant lies ahead.",
      "Things we lose have a way of coming back to us in the end, if not always in the way we expect.",
      "I've always wanted to use that spell.",
      "Just because you're paranoid doesn't mean they aren't after you.",
      "I am not worried, Harry. I am with you.",
      "Ah, music. A magic beyond all we do here.",
      "The world is not divided into good people and Death Eaters.",
      "Curiosity is not a sin. But we should exercise caution with our curiosity.",
      "Fear of a name increases fear of the thing itself.",
      "The best of us must sometimes eat our words.",
      "It is our choices that show what we truly are, far more than our abilities.",
      "I never really gave up on you.",
      "We must all face the choice between what is right and what is easy.",
      "The trouble is, humans do have a knack of choosing precisely those things that are worst for them.",
      "Don't let the Muggles get you down.",
      "The last enemy that shall be destroyed is death.",
      "Indifference and neglect often do much more damage than outright dislike.",
      "Dark and difficult times lie ahead. Soon we must all face the choice between what is right and what is easy.",
      "It does not do to dwell on dreams and forget to live, remember that.",
      "Mischief managed.",
      "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
      "Just because you have the emotional range of a teaspoon doesn't mean we all have.",
      "The scar had not pained Harry for nineteen years. All was well.",
      "It is our choices, Harry, that show what we truly are, far more than our abilities.",
      "The world isn’t split into good people and Death Eaters.",
      "We could all have been killed — or worse, expelled.",
      "I don't go looking for trouble. Trouble usually finds me.",
      "It’s the unknown we fear when we look upon death and darkness, nothing more.",
      "Do not pity the dead, Harry. Pity the living, and above all, those who live without love.",
      "Do not let your past dictate who you are, but let it be part of who you will become.",
      "Happiness can be found in the darkest of times, if one only remembers to turn on the light.",
      "Time will not slow down when something unpleasant lies ahead.",
      "Things we lose have a way of coming back to us in the end, if not always in the way we expect.",
      "I've always wanted to use that spell.",
      "Just because you're paranoid doesn't mean they aren't after you.",
      "I am not worried, Harry. I am with you.",
      "Ah, music. A magic beyond all we do here.",
      "The world is not divided into good people and Death Eaters.",
      "Curiosity is not a sin. But we should exercise caution with our curiosity.",
      "Fear of a name increases fear of the thing itself.",
      "The best of us must sometimes eat our words.",
      "It is our choices that show what we truly are, far more than our abilities.",
      "I never really gave up on you.",
      "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
      "We must all face the choice between what is right and what is easy.",
      "The trouble is, humans do have a knack of choosing precisely those things that are worst for them.",
      "Don't let the Muggles get you down.",
      "The last enemy that shall be destroyed is death.",
      "Indifference and neglect often do much more damage than outright dislike.",
      "Dark and difficult times lie ahead. Soon we must all face the choice between what is right and what is easy.",
      "It does not do to dwell on dreams and forget to live, remember that.",
      "I am a wizard, not a baboon brandishing a stick.",
      "The world isn’t split into good people and Death Eaters.",
      "We could all have been killed — or worse, expelled.",
      "Dark times lie ahead of us and there will be a time when we must choose between what is easy and what is right.",
      "Differences of habit and language are nothing at all if our aims are identical and our hearts are open.",
      "I don't go looking for trouble. Trouble usually finds me.",
      "It’s the unknown we fear when we look upon death and darkness, nothing more.",
      "Do not pity the dead, Harry. Pity the living, and above all, those who live without love.",
      "Do not let your past dictate who you are, but let it be part of who you will become.",
      "Happiness can be found in the darkest of times, if one only remembers to turn on the light.",
      "Time will not slow down when something unpleasant lies ahead.",
      "Things we lose have a way of coming back to us in the end, if not always in the way we expect.",
      "I've always wanted to use that spell.",
      "Just because you're paranoid doesn't mean they aren't after you.",
      "I am not worried, Harry. I am with you.",
      "Ah, music. A magic beyond all we do here.",
      "The world is not divided into good people and Death Eaters.",
      "Curiosity is not a sin. But we should exercise caution with our curiosity.",
      "Fear of a name increases fear of the thing itself.",
      "The best of us must sometimes eat our words.",
      "It is our choices that show what we truly are, far more than our abilities.",
      "I never really gave up on you.",
      "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
      "We must all face the choice between what is right and what is easy.",
      "The trouble is, humans do have a knack of choosing precisely those things that are worst for them.",
      "Don't let the Muggles get you down.",
      "The last enemy that shall be destroyed is death.",
      "Indifference and neglect often do much more damage than outright dislike.",
      "Dark and difficult times lie ahead. Soon we must all face the choice between what is right and what is easy.",
      "It does not do to dwell on dreams and forget to live, remember that.",
      "I am a wizard, not a baboon brandishing a stick.",
      "The world isn’t split into good people and Death Eaters.",
      "We could all have been killed — or worse, expelled.",
      "Dark times lie ahead of us and there will be a time when we must choose between what is easy and what is right.",
      "Differences of habit and language are nothing at all if our aims are identical and our hearts are open.",
      "I don't go looking for trouble. Trouble usually finds me.",
      "It’s the unknown we fear when we look upon death and darkness, nothing more.",
      "Do not pity the dead, Harry. Pity the living, and above all, those who live without love.",
      "Do not let your past dictate who you are, but let it be part of who you will become.",
      "Happiness can be found in the darkest of times, if one only remembers to turn on the light.",
      "Time will not slow down when something unpleasant lies ahead.",
      "Things we lose have a way of coming back to us in the end, if not always in the way we expect.",
      "I've always wanted to use that spell.",
      "Just because you're paranoid doesn't mean they aren't after you.",
      "I am not worried, Harry. I am with you.",
      "Ah, music. A magic beyond all we do here.",
      "The world is not divided into good people and Death Eaters.",
      "Curiosity is not a sin. But we should exercise caution with our curiosity.",
      "Fear of a name increases fear of the thing itself.",
      "The best of us must sometimes eat our words.",
      "It is our choices that show what we truly are, far more than our abilities.",
      "I never really gave up on you.",
      "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
      "You think the dead we loved truly ever leave us?"
    ]
  },
  { id: 7,
    name: 'Hipster', 
    sentences: [
      "I was into __ before it was cool.",
      "Organic kale chips are my spirit snack.",
      "Vinyl records just have that warm sound, you know?",
      "My coffee has to be single-origin, pour-over, and ethically sourced.",
      "I prefer vintage typewriters for that authentic feel.",
      "Sustainable living is my jam.",
      "I ride my fixed-gear bike everywhere.",
      "Craft beer is the only beer for me.",
      "Thrift stores are my fashion runway.",
      "I journal using recycled paper, naturally.",
      "Avocado toast is a breakfast masterpiece.",
      "I find hidden gems in indie movies.",
      "My cat only eats artisanal, small-batch cat food.",
      "I support local artists and makers.",
      "Analog photography captures the soul of the moment.",
      "Polaroid cameras are my way of life.",
      "I brew my own kombucha at home.",
      "Vintage fashion is a form of self-expression.",
      "Minimalism is my lifestyle aesthetic.",
      "I'm all about that plant-based diet.",
      "My room is lit with fairy lights and Edison bulbs.",
      "I curate playlists that tell a story.",
      "Fanny packs are surprisingly practical, okay?",
      "I follow obscure blogs for inspiration.",
      "Artisanal chocolate is my guilty pleasure.",
      "I love getting lost in independent bookstores.",
      "Cacti and succulents are my spirit plants.",
      "I practice mindfulness through daily meditation.",
      "I carry a reusable straw wherever I go.",
      "Vintage video games have a certain charm.",
      "I make my own soy candles.",
      "My fashion style? Effortlessly unique.",
      "I have a collection of antique teacups.",
      "Support your local farmers' market!",
      "I write poems on my vintage typewriter.",
      "I only use a French press for my coffee.",
      "My beard is a work of art.",
      "Thrifted sweaters and flannel shirts, always.",
      "I attend poetry slams and spoken word events.",
      "I've mastered the art of pour-over coffee.",
      "My Instagram is a curated masterpiece.",
      "I find wisdom in old philosophy books.",
      "Carpentry is my meditative hobby.",
      "I prefer obscure indie video games.",
      "Rainy days are meant for cozy reading.",
      "I can't resist collecting antique camera gear.",
      "I brew my own craft cider.",
      "I write code while sipping herbal tea.",
      "Vintage postcards are my preferred souvenirs.",
      "I appreciate street art and muralism.",
      "I'm part of a vinyl record club.",
      "I forage for wild herbs and mushrooms.",
      "Bike rides are my form of therapy.",
      "I organize pop-up art events in my community.",
      "I create custom playlists for every mood.",
      "I've perfected the art of slow cooking.",
      "I find spirituality in stargazing.",
      "Old jazz records are my relaxation soundtrack.",
      "I'm a pro at thrift store furniture finds.",
      "I express myself through abstract gardening.",
      "My laptop sticker game is strong.",
      "I find beauty in decaying urban spaces.",
      "I've embraced the van life mentality.",
      "I design my own eco-friendly clothing.",
      "Indie documentaries are my preferred movies.",
      "I hand-make my own ceramic mugs.",
      "I've never met a farmers' market I didn't like.",
      "I wear sustainable, ethically-made shoes.",
      "I'm all about DIY home renovation.",
      "I create zines about social issues.",
      "I mix my own herbal cocktails.",
      "My mantra: Reduce, Reuse, Recycle.",
      "I find joy in upcycling discarded items.",
      "I practice yoga in nature.",
      "I'm a pro at thrift store vinyl hunting.",
      "I find artistry in urban street fashion.",
      "I restore vintage bicycles as a hobby.",
      "I make my own natural skincare products.",
      "I find inspiration in abandoned places.",
      "I've mastered the art of urban foraging.",
      "I hand-embroider my own clothing.",
      "I document my travels through Polaroids.",
      "I host underground supper club events.",
      "I can identify obscure constellations.",
      "I'm all about that DIY homebrewing.",
      "I wear glasses with non-prescription lenses.",
      "I only use old-school film cameras.",
      "I've turned my balcony into a mini garden.",
      "I've perfected the art of homemade sourdough.",
      "I'm a regular at open mic poetry nights.",
      "I collect antique keys and locks.",
      "I brew my own unique kombucha flavors.",
      "I dabble in experimental art installations.",
      "I've embraced the concept of slow fashion.",
      "I'm all about sustainable urban beekeeping.",
      "I find creativity in upcycled home decor.",  
    ]
  },
  { id: 8, 
    name: 'Hockey', 
    sentences: [
      "He's got hands like a magician.",
      "That was a wicked slapshot!",
      "The goalie stood on his head tonight.",
      "The enforcer dropped the gloves and threw some haymakers.",
      "The power play unit was on fire.",
      "He deked out the defenseman and scored a beauty.",
      "The team pulled off a hat trick of wins.",
      "They're playing dump and chase tonight.",
      "The game went into sudden death overtime.",
      "He sniped that shot into the top corner.",
      "The player got sent to the sin bin for roughing.",
      "The ref let a lot of stuff go in this game.",
      "The arena was rocking with the home crowd's energy.",
      "The coach gave them a pep talk during intermission.",
      "He got a Gordie Howe hat trick with a goal, an assist, and a fight.",
      "The defenseman made a great poke check to break up the play.",
      "The goalie made a sprawling save with his pad.",
      "The player got a breakaway and went five-hole for the goal.",
      "The team's penalty kill was on point tonight.",
      "He's got a rocket of a slapshot.",
      "The player got stoned by the goalie on the breakaway.",
      "The game ended in a 2-2 tie after regulation.",
      "The captain dropped the ceremonial puck before the game.",
      "He dangled through the entire defense and scored.",
      "The team is in a slump right now.",
      "The rookie is making a big impact in his first season.",
      "The player got ejected for arguing with the ref.",
      "The goalie made a desperation glove save.",
      "The team is on a winning streak.",
      "He got caught cherry picking at the blue line.",
      "The player got a game misconduct for a dangerous hit.",
      "The arena's glass got shattered after a big hit.",
      "The player got a two-minute minor for high-sticking.",
      "The team's offense is firing on all cylinders.",
      "He's got a cannon for a shot.",
      "The defenseman cleared the puck off the glass.",
      "The player got tripped up and drew a penalty.",
      "The team is in the basement of the standings.",
      "He got his bell rung after the big hit.",
      "The goalie made a flashy glove save to rob the shooter.",
      "The player got a five-minute major for fighting.",
      "The team's defensive structure is solid.",
      "He pulled off a spin-o-rama move on the breakaway.",
      "The player got a hat trick in the first period.",
      "The game went to a shootout to decide the winner.",
      "The team's power play is struggling lately.",
      "He got benched for taking a bad penalty.",
      "The player got a diving penalty after embellishing a trip.",
      "The team's fans are chanting and banging thundersticks.",
      "He got a slashing penalty for breaking the opponent's stick.",
      "The player got a wraparound goal by sneaking the puck past the goalie's pad.",
      "The team's blue line is solidifying the defense.",
      "He got a cross-checking penalty for shoving an opponent from behind.",
      "The player got a beauty of an assist on the goal.",
      "You skate like a newborn giraffe!",
      "Do you even know how to hold a stick?",
      "Nice attempt, but you're still a benchwarmer.",
      "Are you lost? This is a hockey rink, not a daycare.",
      "You shoot like a grandma with arthritis.",
      "Is this your first time on ice? It sure looks like it.",
      "I've seen more skill in a peewee league.",
      "You're slower than a Zamboni on a coffee break.",
      "Do they make participation trophies for your level of play?",
      "You're as effective as a hockey puck made of feathers.",
      "If you were any softer, you'd be a hockey pillow.",
      "Do you need a map to find the goal?",
      "I've taken harder hits from a snowflake.",
      "Maybe try golf – less skating involved.",
      "The way you play is a crime against hockey.",
      "I've seen better stickhandling from a blindfolded toddler.",
      "Do you practice missing the net, or does it come naturally?",
      "You're the reason they invented offside rules.",
      "Did you learn to skate in a figure skating class?",
      "Even the goalie has better hands than you.",
      "I've seen more fight in a frozen pizza.",
      "You're like a hockey puck – always getting slapped around.",
      "Did you mistake the puck for a hot potato?",
      "You must be a goalie because you're letting everyone down.",
      "Your shot has less accuracy than a broken compass.",
      "Hockey is a team sport, but I guess you didn't get the memo.",
      "You're a legend... in your own mind.",
      "They should put your face on the penalty box for crimes against hockey.",
      "I've seen more intensity in a game of checkers.",
      "Even the Zamboni has smoother moves than you.",
      "Skating backwards suits you – your skills aren't worth facing forward.",
      "Do you need a magnifying glass to find the puck?",
      "Did you learn to play from a how-not-to manual?",
      "You make the ice look crowded... because everyone's avoiding you.",
      "Do you believe in miracles? You need one to win.",
      "I've seen better defense from a cardboard cutout.",
      "You're like a broken stick – utterly useless.",
      "You're the MVP of making excuses.",
      "Do you think they have a mercy rule for your performance?",
      "Are you auditioning for the worst player award?",
      "You're so bad, even the referees feel sorry for you.",
      "Can I get your autograph? I've never seen someone fail so spectacularly.",
      "Do you practice missing the net, or does it come naturally?",
      "I've seen better hockey sense in a potted plant.",
      "You must be a master of tripping over your own feet.",
      "Did you invent a new skating technique? Because it's awful.",
      "You're like a puck magnet – except for when it actually matters.",
      "Even a scarecrow has better stickhandling skills.",
      "I didn't know they allowed penguins to play hockey.",
      "You're like a goalie's favorite target – wide open.",
      "Do they have a penalty for embarrassing the sport?",
      "They should put you in the penalty box for that play.",
      "I've seen better aim from a blindfolded archer.",
      "Your passes are a work of art... if the goal is abstract failure.",
      "Is your stick made of rubber? How else do you explain those bounces?",
      "I've seen smoother skating from a newborn deer.",
      "You must be a secret agent, trying to sabotage your own team.",
      "You're the reason they invented face masks – to hide your shame.",
      "Do they make skates in clown sizes? You'd fit right in.",
      "Even a broken clock is right twice a day – you're never right.",
      "Did you learn to play from a how-not-to manual?",
      "You're so offside, even GPS can't locate your position.",
      "You're like a goalie's nightmare – unpredictable and easy to beat.",
      "Do they have a mercy rule for your level of incompetence?",
      "I've seen better hustle from a sloth.",
      "Did you mistake the puck for a hot potato?",
      "You're like a living highlight reel of failures.",
      "Are you trying to set a record for the least time spent on the ice?",
      "You must be a coach's favorite – an example of what not to do.",
      "I've seen better strategy in a game of rock-paper-scissors.",
      "Do you have a strategy, or are you just winging it? Badly.",
      "You're like a puck black hole – everything gets sucked away from you.",
      "Is your stick made of spaghetti? Your shots are that weak.",
      "I've seen better coordination in a group of intoxicated penguins.",
      "You must have a sixth sense – for choosing the worst possible play.",
      "Do you think they give out awards for participation in mediocrity?",
      "You're like a traffic cone out there – players just skate around you.",
    "Is your strategy to tire out the other team from laughing?",
      "You must be a goalie's favorite shooter – so predictable.",
      "I've seen better endurance in a game of musical chairs.",
      "Do you get a prize for making the fewest passes in a game?",
      "You're like a case study in how not to play hockey.",
      "Is your jersey number the same as your IQ? Single digits?",
      "You must be trying to set a record for most turnovers in a game.",
      "I've seen better skating in a figure skating show.",
      "Do you practice falling down, or does it come naturally?",
      "You're like a spectator on ice – just watching the game go by.",
      "Is your stick made of marshmallow? Your shots are that soft.",
      "You must be a secret agent for the other team.",
      "I've seen better defense in a game of tag.",
      "Do you think they have a 'worst player' award? You'd win.",
      "You're like a goalie's best friend – easy to stop.",
      "Is your strategy to confuse your own teammates?",
      "You must be sponsored by the penalty box at this point.",
      "I've seen better sportsmanship in a game of Monopoly.",
      "Do you ever plan to shoot on net? Or is missing your goal?",
      "You're like a case study in poor decision-making.",
      "Is your stick made of rubber? Your shots bounce everywhere.",
      "You must be auditioning for the role of team jester.",
      "I've seen better moves from a cardboard cutout.",
      "Do you ever feel bad about taking ice time away from someone better?",
      "You're like a magnet for bad luck on the ice.",
      "Is your strategy to give the other team a head start?",
      "You must be the reason they invented the phrase 'own goal.'",
      "I've seen better reflexes from a sloth.",
      "Do you think they have a 'least valuable player' trophy?",
      "You're like a turnover vending machine – always giving them out.",
      "Is your stick made of lead? Your shots have no power.",
      "You must be a professional at making the wrong choices.",
      "I've seen better aim from a blindfolded dart player.",
      "Do you ever wonder if your skates are on the wrong feet?",
      "You're like a scarecrow in the goal – anything can get past you.",
      "Is your strategy to confuse yourself? It's working.",
      "You must be on a mission to make every play fail.",
      "I've seen better balance from a newborn foal.",
      "Do you practice losing, or does it come naturally?",
      "Do you ever dream of scoring goals? Or do nightmares count?",
      "You're like a player version of a black hole – all offense disappears.",
      "Is your stick made of paper? Your shots are that soft.",
      "You must be a coach's nightmare – a walking disaster.",
      "I've seen better footwork from a penguin.",
      "Do you practice being out of position, or does it come naturally?",
      "You're like a goalie's best friend – predictable and easy.",
      "Is your strategy to make every game a comedy show?",
      "You must be aiming for the 'worst player' trophy.",
      "I've seen better leadership from a pack of lost puppies.",
      "Do you ever think about improving? It's never too late to start.",
      "You're like a one-person circus out there – entertaining for all the wrong reasons.",
      "Is your stick made of foam? Your shots are that light.",
      "You must be a ref's favorite – constant penalties.",
      "I've seen better coordination from a group of toddlers.",
      "Do you ever plan to make a good play? I'm not holding my breath.",
      "You're like a bad luck charm for your own team.",
      "Is your strategy to be a disappointment to your fans?",
      "You must be trying to set records for worst stats.",
      "I've seen better sportsmanship from a sore loser.",
      "Do you ever think about quitting? It might be for the best.",
      "You're like a goalpost's shadow – always getting in the way.",
      "Is your stick made of rubber? Your shots bounce off everything.",
      "You must be a magnet for bad luck on the ice.",
      "I've seen better reflexes from a sleeping sloth.",
      "Do you ever wonder if your skates are made of butter?",
      "You're like a goalie's favorite shooter – no challenge at all.",
      "Is your strategy to be the reason for your team's downfall?",
      "You must be auditioning for the role of team jokester.",
      "I've seen better decisions made by a Magic 8-Ball.",
      "Do you ever wonder if you were meant to play a different sport?",
      "You're like a one-person comedy show – just not intentionally funny.",
      "Is your stick made of foam? Your shots have no power.",
      "You must be allergic to winning games.",
    ]
  },
  { id: 9,
    name: 'Hippie', 
    sentences: [
      "Peace and love, man.",
      "Groovy vibes all around.",
      "Let your soul shine.",
      "Chill out and go with the flow.",
      "Spread positive energy like confetti.",
      "Tune in, turn on, drop out.",
      "Make art, not war.",
      "The universe is our cosmic playground.",
      "Dude, life is a beautiful trip.",
      "Embrace the power of flower.",
      "Feel the rhythm of the earth.",
      "Namaste, fellow traveler.",
      "Free your mind and the rest will follow.",
      "Hug trees, they've got good energy.",
      "Radiate good vibes like the sun.",
      "Keep on truckin'.",
      "Dance like nobody's watching.",
      "Love is all you need.",
      "Find your own path through the wildflowers.",
      "Smile at strangers and watch the magic happen.",
      "Breathe deep and let it all go.",
      "Keep the faith and spread the love.",
      "Question authority and seek truth.",
      "Peace, love, and granola.",
      "Be the rainbow in someone's cloudy day.",
      "Plant seeds of kindness everywhere.",
      "Let your heart chakra shine.",
      "Turn negatives into positives.",
      "Stay trippy, little hippie.",
      "Embrace the rhythm of the universe.",
      "Feel the energy of the cosmos within.",
      "Float on the river of life.",
      "Dream big and reach for the stars.",
      "Celebrate the beauty of diversity.",
      "Make love, not war.",
      "Rainbows are nature's artwork.",
      "Be gentle with the earth and its creatures.",
      "Peaceful minds create peaceful lives.",
      "Follow the wind to new adventures.",
      "Spread love like wildflowers.",
      "Stay high on life's positive vibes.",
      "Let your soul dance to its own tune.",
      "Embrace the mystery of the unknown.",
      "Let your inner light shine.",
      "Happiness is a journey, not a destination.",
      "Be a warrior of light and love.",
      "Live in harmony with the natural world.",
      "Radiate positivity like the sun's rays.",
      "Love is the ultimate renewable resource.",
      "Find your tribe and love them hard.",
      "Life is about the journey, not the stuff.",
      "Choose love over fear, every time.",
      "Spread smiles like wildflower seeds.",
      "Keep the earth clean, it's not Uranus.",
      "The universe is conspiring in your favor.",
      "Be kind to your mind and body.",
      "Embrace the energy of the full moon.",
      "Let your spirit soar like an eagle.",
      "Find beauty in the simplest moments.",
      "Nature is the best therapy.",
      "Create more, consume less.",
      "Love and be loved; it's all we need.",
      "Live like a tree, grounded and free.",
      "Imagine a world fueled by love.",
      "Stay groovy even when times are tough.",
      "Channel your inner flower child.",
      "The answer, my friend, is blowing in the wind.",
      "Love is free, spread it generously.",
      "Let go of worries like leaves in the wind.",
      "Float through life with a grateful heart.",
      "Tune into the frequency of love.",
      "The Earth is our mother; treat her kindly.",
      "Follow the sun wherever it may lead.",
      "Let your heart be your compass.",
      "Stay wild, stay true, stay you.",
      "Life's a journey; enjoy the ride.",
      "The energy you give is the energy you get.",
      "Happiness blooms from within.",
      "Spread positivity like wildfire.",
      "Peaceful thoughts create a peaceful world.",
      "Dance to the rhythm of your own heartbeat.",
      "Embrace the magic in everyday moments.",
      "Let love and kindness rule your actions.",
      "Celebrate the interconnectedness of all life.",
      "Smile often; it's a universal language.",
      "Live freely, love deeply, laugh often.",
      "Find your inner peace and let it radiate.",
      "Create your own sunshine on cloudy days.",
      "Love is the truest form of wealth.",
      "Be the change you wish to see.",
      "Nature is a masterpiece; admire it often.",
      "Let the energy of the earth heal you.",
      "Radiate love like the sun radiates light.",
      "Embrace the wisdom of the ancient trees.",
      "Choose happiness like it's a daily outfit.",
      "Kindness is a language everyone understands.",
      "Stay positive even when life's a bumpy ride.",
      "Let your soul be your guide.",
      "Love and let love; it's that simple.",
      "Be a sunflower in a field of daisies.",
      "Find balance in the chaos of existence.",
      "Spread good vibes like a contagious smile.",
    ]
  },
  { id: 10,
    name: 'New Yorker', 
    sentences: [
      "Hey, I'm walkin' here!",
      "Fuhgeddaboudit!",
      "I'll take a slice.",
      "What's the dealio?",
      "Are you kiddin' me?",
      "Get outta here!",
      "I'm starvin' over here.",
      "Cawfee",
      "The subway's delayed again.",
      "I live in the city that never sleeps.",
      "Taxi!",
      "Bodega run",
      "Let's grab a bagel and lox.",
      "You from 'round here?",
      "I'm gonna catch a Broadway show.",
      "I can't believe the rent prices.",
      "It's rush hour, avoid Times Square.",
      "Wait on line",
      "I need a pretzel from a street cart.",
      "I'm a Yankees/Mets fan.",
      "The Empire State Building is a must-see.",
      "The hot dog stands have the best dogs.",
      "I'm going to the Met today.",
      "Mind the puddle.",
      "This city has the best food.",
      "Let's take the Staten Island Ferry.",
      "I'm taking the L train.",
      "Watch out for rats in the subway.",
      "Let's meet in Central Park.",
      "It's so crowded in Times Square.",
      "The Knicks/Nets game was intense.",
      "I'm running late because of traffic.",
      "I love the High Line park.",
      "Brooklyn Bridge is beautiful at sunset.",
      "I can't find decent pizza anywhere else.",
      "I'm hitting up the bars in Williamsburg.",
      "Doorman building",
      "Let's do brunch on Sunday.",
      "I'm headed to Coney Island this weekend.",
      "The weather's perfect for a rooftop party.",
      "I need a MetroCard refill.",
      "I'm shopping on 5th Avenue.",
      "I'm grabbing halal from the food truck.",
      "Let's rent bikes and ride along the Hudson.",
      "Uptown or downtown?",
      "I'm walking the dog in Riverside Park.",
      "The Guggenheim is my favorite museum.",
      "I'm seeing the Rockettes at Radio City.",
      "Let's go to Smorgasburg for food.",
      "I'm taking the A/C/E trains.",
      "The Village has the best jazz clubs.",
      "I'm exploring the neighborhoods of Brooklyn.",
      "I'm going to the Bronx Zoo.",
      "Can you pass me a knish?",
      "I'm jogging in Prospect Park.",
      "Let's grab a dirty water hot dog.",
      "The 6 train is always packed.",
      "I'm headed to Chinatown for lunch.",
      "The rents are too damn high!",
      "I'm people-watching in Washington Square Park.",
      "I'm checking out the street art in Bushwick.",
      "Let's take the Roosevelt Island Tramway.",
      "I'm window shopping on Madison Avenue.",
      "The bagels here are the best.",
      "I'm exploring the galleries in Chelsea.",
      "I'm stuck in traffic on the BQE.",
      "Let's grab a slice at Joe's Pizza.",
      "I'm taking a yoga class in DUMBO.",
      "I'm going to the Museum of Natural History.",
      "Let's catch a show at Bowery Ballroom.",
      "I'm getting pierogi in Greenpoint.",
      "The subway is so unpredictable.",
      "I'm hitting up the bars in the East Village.",
      "I'm commuting via the Long Island Railroad.",
      "The hot pretzels smell amazing.",
      "Let's walk across the Williamsburg Bridge.",
      "I'm browsing the shops in SoHo.",
      "I'm picnicking in Prospect Park.",
      "Let's go to a comedy show in the LES.",
      "The falafel carts have the best falafels.",
      "I'm taking the F/M/J/Z trains.",
      "The traffic on the FDR is terrible.",
      "Let's grab some food from Eataly.",
      "I'm catching a flight at JFK.",
      "I'm sunbathing in Rockaway Beach.",
      "I'm getting a slice at Grimaldi's.",
      "I'm exploring the food scene in Astoria.",
      "The view from the Top of the Rock is amazing.",
      "I'm going to the New York Botanical Garden.",
      "Let's hit up some happy hour specials.",
      "I'm chilling at the South Street Seaport.",
      "I'm taking the 7 train to Flushing.",
      "I'm getting some cheesecake from Junior's.",
      "I'm catching a show at the Apollo Theater.",
      "I'm heading to Roosevelt Island.",
      "I'm grabbing a pastrami sandwich from Katz's Deli.",
      "The Halal Guys have the best chicken over rice.",
      "I'm taking the G train.",
      "Let's explore the shops in Williamsburg.",
      "I'm jogging on the Hudson River Greenway.",
      "I'm getting some knishes from Yonah Schimmel's.",  
    ]
  },
  { id: 11,
    name: 'Pirate', 
    sentences: [
      "Ahoy, matey!",
      "Avast ye!",
      "Shiver me timbers!",
      "Yo ho ho and a bottle of rum!",
      "Land ho!",
      "Thar she blows!",
      "Aye aye, captain!",
      "Batten down the hatches!",
      "Dead men tell no tales.",
      "Savvy?",
      "Walk the plank!",
      "Blow me down!",
      "Heave ho!",
      "Jolly Roger",
      "Pieces of eight",
      "X marks the spot!",
      "Swab the deck!",
      "Keelhaul!",
      "Thar be treasure!",
      "Black spot",
      "Ahoy, me hearties!",
      "Cast off!",
      "Thar be monsters!",
      "Scallywag",
      "Buccaneer",
      "Lubber",
      "Avast, ye scallywags!",
      "Scurvy dog",
      "Treasure map",
      "Me treasure chest!",
      "Crows nest",
      "Landlubber",
      "Shipshape and Bristol fashion!",
      "Sail ho!",
      "Thar be gold in them waters!",
      "Fire in the hole!",
      "Aye, aye, matey!",
      "Poop deck",
      "Thar be rough seas ahead!",
      "All hands on deck!",
      "Blimey!",
      "Scuttlebutt",
      "Thar be a storm brewin'!",
      "Cannonball!",
      "No prey, no pay.",
      "Down to Davy Jones' locker!",
      "Raise the Jolly Roger!",
      "Belay that!",
      "Thar be cursed treasure!",
      "Man overboard!",
      "Thar be mermaids singin'!",
      "Cap'n",
      "Land ho, me hearties!",
      "Thar be a mutiny!",
      "Aye, aye, captain!",
      "Swashbucklin'",
      "Thar be a kraken!",
      "Aye, the wind be at our backs!",
      "Thar be hidden riches!",
      "Hard to starboard!",
      "Landlubber",
      "Thar be a ghost ship!",
      "Avast, ye mateys!",
      "Thar be a sea serpent!",
      "Shark bait",
      "Sail ho, off the port bow!",
      "Thar be forbidden waters!",
      "Strike the colors!",
      "Scurvy",
      "Davy Jones' locker",
      "Thar be a siren's call!",
      "Weigh anchor!",
      "Thar be a becalming!",
      "Booty",
      "Thar be a marooning!",
      "Hoist the anchor!",
      "Thar be a naval battle!",
      "Salty",
      "Thar be a lagoon!",
      "Crow's nest",
      "Thar be a trade wind!",
      "Doubloons",
      "Thar be a pirate code!",
      "Lad",
      "Thar be a mermaid's tears!",
      "Matey",
      "Thar be a booty haul!",
      "Land ho, ye scallywags!",
      "Thar be a parrot on me shoulder!",
      "Sea legs",
      "Thar be a compass point!",
      "Buccaneer",
      "Thar be a treasure chest!",
      "Matey",
      "Thar be a doubloon!",
      "Jolly Roger",
      "Thar be a cutlass!",
      "Arrr!",
      "Thar be a schooner!",
      "Bilge rat",
      "Thar be a galleon!",
      "Poop deck",
      "Thar be a plunder!",
    ]
  },
  { id: 12,
    name: 'Rasta', 
    sentences: [
      "One Love, One Heart.",
      "Positive vibrations all around.",
      "Irie vibes, always.",
      "Jah bless and guide.",
      "Let the music heal your soul.",
      "No worries, just blessings.",
      "Respect the earth and its creatures.",
      "Unity in diversity.",
      "Embrace the rhythm of life.",
      "Live in harmony with nature.",
      "Bless up, every time.",
      "Give thanks for each day.",
      "Spread love like wildfire.",
      "Lively up yourself, don't be no drag.",
      "Chase away the negative vibes.",
      "Smile through the storm.",
      "Keep your heart light as a feather.",
      "Walk in the sunshine of positivity.",
      "Roots and culture, always.",
      "Let your soul shine.",
      "Keep your spirit high.",
      "Stand tall like a palm tree.",
      "Cool and calm in every situation.",
      "Let love and kindness rule.",
      "Live life to the fullest, every day.",
      "Dance to the rhythm of your heart.",
      "Let the good vibes multiply.",
      "Cherish every moment.",
      "Seek truth and wisdom.",
      "Live with purpose and passion.",
      "Blessings flow like a river.",
      "Nurture your mind, body, and soul.",
      "Be a beacon of light.",
      "Follow the path of righteousness.",
      "Let go of worries, embrace peace.",
      "Let your spirit soar like an eagle.",
      "Spread positivity like wildfire.",
      "Give thanks for the journey.",
      "Embrace change with an open heart.",
      "Love and unity over everything.",
      "Keep the fire of hope burning.",
      "Cherish your loved ones deeply.",
      "Be the change you wish to see.",
      "Stay humble on the mountaintop.",
      "Let the music of life uplift you.",
      "Inhale courage, exhale fear.",
      "Life is a gift, unwrap it joyfully.",
      "Radiate love in every direction.",
      "Connect with the energy of the universe.",
      "Be present in every moment.",
      "Cultivate a garden of positivity.",
      "Embrace the mystery of life.",
      "Rise above the storms of life.",
      "Stay true to your roots.",
      "Walk the path of enlightenment.",
      "Let your heart guide your journey.",
      "Positive thoughts, positive life.",
      "Live in the rhythm of the universe.",
      "Jah's love knows no bounds.",
      "Let your soul dance to the music.",
      "Empower yourself and others.",
      "Keep your faith unshakable.",
      "Blessings rain down like a waterfall.",
      "Respect all, harm none.",
      "Embrace the richness of the earth.",
      "Be a voice of reason and love.",
      "Savor the sweetness of life.",
      "Let your light shine through.",
      "Radiate good vibes always.",
      "Find strength in unity.",
      "Plant seeds of positivity.",
      "Celebrate life's blessings.",
      "Embrace the fullness of your being.",
      "Keep your mind clear like the sky.",
      "Love is the ultimate answer.",
      "Let peace be your constant companion.",
      "Stay strong in the face of adversity.",
      "Seek knowledge and understanding.",
      "Let your spirit be your guide.",
      "Harmony in diversity.",
      "Nurture your soul with goodness.",
      "Embrace the power of now.",
      "Let your heart be your compass.",
      "Love guides every step.",
      "Stay grounded like the trees.",
      "Trust the journey you're on.",
      "Keep your energy positive and pure.",
      "Chase away negativity with love.",
      "Stay kind, stay humble.",
      "Live your truth with courage.",
      "Let go and let Jah.",
      "Dwell in love and gratitude.",
      "Radiate positive energy.",
      "Unity is strength, division is weakness.",
      "Embrace the mysteries of the universe.",
      "Blessings manifest in abundance.",
      "Spread love like wildfire.",
      "Be a beacon of light in darkness.",
      "Embrace the interconnectedness of all life.",
      "Keep your heart open and free.",
      "Jah's love is ever-present.",
      "Live with intention and purpose.",
      "Let your soul sing its song.",
      "Trust in the divine plan.",
      "Stay true to your inner self.",
      "Embrace the beauty of diversity.",    
    ]
  },
  { id: 13,
    name: 'Surfer', 
    sentences: [
      "Hang ten!",
      "Cowabunga, dude!",
      "Ride the wave!",
      "Catch a gnarly barrel!",
      "Dropping in!",
      "Shred it!",
      "Totally tubular!",
      "Stoked beyond belief!",
      "Wipeout!",
      "Radical moves!",
      "Surf's up!",
      "Rip it up!",
      "Dawn patrol session!",
      "Charging the swell!",
      "Carving it up!",
      "Big kahuna!",
      "Riding the face!",
      "Hanging loose!",
      "Wave of a lifetime!",
      "Getting pitted!",
      "Barrel riding!",
      "Sick waves!",
      "Going vertical!",
      "Chasing the line!",
      "Riding high!",
      "Tube time!",
      "Nose riding!",
      "Walking the board!",
      "Swingin' spray!",
      "Finding the sweet spot!",
      "Getting air!",
      "Surfer's paradise!",
      "Waxed up and ready!",
      "Salty vibes!",
      "Wave warrior!",
      "Rider's paradise!",
      "Sun, surf, and sand!",
      "Sunset session!",
      "Riding the foam!",
      "Living the endless summer!",
      "Saltwater therapy!",
      "Surfing sensation!",
      "Soul surfer!",
      "Riding nature's roller coaster!",
      "Golden hour glide!",
      "Board meeting on the waves!",
      "Styling and profiling!",
      "Sandy toes, salty kisses!",
      "Carving the canvas!",
      "Sea breeze bliss!",
      "Surfing safari!",
      "Riding with the tide!",
      "Oceanic adventure!",
      "Waves of joy!",
      "Finding the pocket!",
      "Chasing liquid dreams!",
      "Sunrise surf session!",
      "Charging the break!",
      "Saltwater soul!",
      "Waves of freedom!",
      "Epic rides and good vibes!",
      "Barrel dodger!",
      "Sandy-haired soul!",
      "Riding the edge!",
      "Board whisperer!",
      "Sunkissed and stoked!",
      "Paddle battle!",
      "Hangin' at the lineup!",
      "Saltwater therapy!",
      "Gliding with grace!",
      "Eternal surf life!",
      "Waves of serenity!",
      "Dropping into life!",
      "Finding the line!",
      "Salt in the air, sand in my hair!",
      "Catching liquid energy!",
      "Riding the liquid mountains!",
      "Walking on water!",
      "Sunset sliders!",
      "Charging the liquid hills!",
      "Salty hair, don't care!",
      "Riding the azure curls!",
      "Sunrise sliders!",
      "Sea, surf, and sun!",
      "Paddle out, paddle in!",
      "Saltwater seeker!",
      "Gone surfin'!",
      "Sea spray dreams!",
      "Epic swells and ocean spells!",
      "Riding with the dolphins!",
      "Sunset shredder!",
      "Saltwater symphony!",
      "Waves of exhilaration!",
      "Riding the wild blue!",
      "Sandy playground!",
      "Chasing the perfect wave!",
      "Epic sets and sunsets!",
      "Riding the liquid roller coaster!",
      "Waves of pure bliss!",
      "Carving the liquid canvas!",  
    ]
  },
  { id: 14,
    name: 'Stoner', 
    sentences: [
      "Blazin' it up",
      "Chillin' with Mary Jane",
      "Elevating my thoughts",
      "Going green",
      "High on life",
      "Puff, puff, pass",
      "Inhale the good stuff",
      "Cannabis connoisseur",
      "Dank dreams",
      "Rollin' in the haze",
      "Mindful tokes",
      "Stoned and serene",
      "Living the high life",
      "Baked and amazed",
      "Stashin' the stash",
      "Sparkin' up joy",
      "Potent perspectives",
      "Hashin' it out",
      "Sativa sensations",
      "Getting lit",
      "Blissful bowls",
      "Smokin' sensibilities",
      "Ganja giggles",
      "Chronic contemplations",
      "Mellow musings",
      "Toke and transcend",
      "Reefer reflections",
      "Zen and zooted",
      "Laid-back tokes",
      "Marijuana moments",
      "Couch-lock chronicles",
      "Indica insights",
      "Bud-driven brainstorm",
      "Cannabis creations",
      "High-minded adventures",
      "Joint exploration",
      "Euphoric escapades",
      "Weed wisdom",
      "Pot-fueled epiphanies",
      "THC therapy",
      "Lifting off",
      "Vibin' with the herb",
      "Canna-curious",
      "Blissful haze",
      "Mindful marijuana",
      "Rolling relaxation",
      "Ganja guides",
      "Sticky situations",
      "Chronic vibes",
      "Elevated existence",
      "Peaceful puffing",
      "Recreational relaxation",
      "Spiritual spliffs",
      "Cannabis catharsis",
      "Higher horizons",
      "Nature's nectar",
      "Aromatic adventures",
      "Chasing cannabis clouds",
      "Ganja gratitude",
      "Hash haven",
      "Blunt blessings",
      "Hemp highs",
      "Inner journey, outer space",
      "Marijuana magic",
      "Edibles escapade",
      "Bud-blessed euphoria",
      "Herb-powered happiness",
      "Toke-induced introspection",
      "Cosmic contemplation",
      "Enlightened inhalation",
      "Rolling with the green",
      "Soulful smoke sessions",
      "Bong water wisdom",
      "Elevated energy",
      "Joint-venture joy",
      "Cannabis connection",
      "Zen zephyrs",
      "Budding enlightenment",
      "Inhaling inspiration",
      "Ganja gurus",
      "Trippy tokes",
      "Weeded wanderlust",
      "Conscious cannabis",
      "High-frequency healing",
      "Mindful munchies",
      "Plant-powered pondering",
      "Blissful bong rips",
      "Vibrational elevation",
      "Inner peace inhaled",
      "Enlightened edibles",
      "Spiritual spliffing",
      "Ganja-guided meditation",
      "Herbal highs",
      "Euphoric exhales",
      "Cannabis crescendo",
      "Toke and tranquility",
      "Harmonious hemp",
      "Bud-blessed vibes",
      "Cosmic contemplations",
      "Elevated explorations",
      "Sensory sensation",
      "Green goddess gatherings",
      "Baked brilliance",
      "Mindful Mary Jane",
      "Peaceful puffery"    
    ]
  },
  { id: 15,
    name: 'Star Wars',
    sentences: [
      "May the Force be with you.",
      "I have a bad feeling about this.",
      "It's a trap!",
      "Help me, Obi-Wan Kenobi. You're my only hope.",
      "I find your lack of faith disturbing.",
      "Do or do not, there is no try.",
      "The Force will be with you, always.",
      "I am your father.",
      "No, I am your father.",
      "Fear is the path to the dark side. Fear leads to anger, anger leads to hate, hate leads to suffering.",
      "The dark side of the Force is a pathway to many abilities some consider to be unnatural.",
      "You were the chosen one!",
      "These aren't the droids you're looking for.",
      "I love you. I know.",
      "In my experience, there's no such thing as luck.",
      "Chewie, we're home.",
      "I've got a bad feeling about this.",
      "I am the Senate.",
      "So this is how liberty dies… with thunderous applause.",
      "It's treason, then.",
      "I don't like sand. It's coarse and rough and irritating and it gets everywhere.",
      "You can't stop the change, any more than you can stop the suns from setting.",
      "This is a new day, a new beginning.",
      "You can't hide forever.",
      "There's always a bigger fish.",
      "I'll try spinning, that's a good trick.",
      "I'm just a simple man trying to make my way in the universe.",
      "It's the ship that made the Kessel Run in less than twelve parsecs.",
      "Aren't you a little short for a stormtrooper?",
      "I am fluent in over six million forms of communication.",
      "Stay on target.",
      "A Jedi's strength flows from the Force.",
      "Why, you stuck-up, half-witted, scruffy-looking nerf herder!",
      "So, who talks first? You talk first? I talk first?",
      "The garbage'll do.",
      "Traveling through hyperspace ain't like dusting crops, farm boy.",
      "I'll never turn to the dark side. You've failed, your highness. I am a Jedi, like my father before me.",
      "I am one with the Force, and the Force is with me.",
      "Rebellions are built on hope.",
      "Your focus determines your reality.",
      "This is not going to go the way you think.",
      "Hope is like the sun. If you only believe in it when you can see it, you'll never make it through the night.",
      "The belonging you seek is not behind you, it is ahead.",
      "The Force is strong with this one.",
      "This party's over.",
      "There is no death, there is the Force.",
      "Remember... the Force will be with you, always.",
      "I suggest a new strategy, R2: let the Wookiee win.",
      "I am C-3PO, human-cyborg relations.",
      "There's too many of them!",
      "You were my brother, Anakin. I loved you.",
      "If you strike me down, I shall become more powerful than you can possibly imagine.",
      "He's no good to me dead.",
      "Size matters not. Judge me by my size, do you?",
      "Great, kid. Don't get cocky.",
      "I'm not a committee!",
      "That's not how the Force works!",
      "I sense a disturbance in the Force.",
      "Now, young Skywalker, you will die.",
      "The Force is with you, young Skywalker, but you are not a Jedi yet.",
      "You can kill me, but you will never destroy me. It takes strength to resist the dark side. Only the weak embrace it.",
      "The Force isn't with you, young one.",
      "Your overconfidence is your weakness.",
      "Your faith in your friends is yours.",
      "I'm a Jedi. Like my father before me.",
      "I'm one with the Force. The Force is with me.",
      "I'm not afraid.",
      "I fear nothing. For all is as the Force wills it.",
      "I have the high ground.",
      "There is always hope.",
      "The Force brought us together.",
      "Let the past die. Kill it, if you have to.",
      "I am no Jedi.",
      "I won't let them win.",
      "The Force is calling to you. Just let it in.",
      "The galaxy is full of stories.",
      "Hope is the spark that'll light the fire that'll burn the First Order down.",
      "We are the spark, that will light the fire that'll burn the First Order down.",
      "Confronting fear is the destiny of a Jedi.",
      "The Force wills it.",
      "They fly now?",
      "Amazing. Every word of what you just said was wrong.",
      "The Force brought me here.",
      "I will finish what you started.",
      "I'm Rey Skywalker.",
      "Balance in the Force.",
      "We've passed on all we know. A thousand generations live in you now.",
      "The Force is strong in my family. My father has it. I have it. My sister has it.",
      "Rey, some things are stronger than blood.",
      "The Force will be with you, always."    
    ]
  },
  { id: 16,
    name: 'Geek',
    sentences: [
      "It's not a bug, it's a feature.",
      "404: Brain not found.",
      "There's no place like 127.0.0.1",
      "I need more RAM.",
      "There are 10 types of people: those who understand binary and those who don't.",
      "sudo rm -rf /",
      "To code or not to code, that is the question.",
      "I CTRL you.",
      "Keep calm and debug on.",
      "I'm not lazy, I'm in energy-saving mode.",
      "Code is poetry.",
      "I'm not a nerd, I'm just smarter than you.",
      "I void warranties.",
      "I'm the root of all problems.",
      "Error 404: Motivation not found.",
      "I'm silently correcting your grammar.",
      "Geek by day, gamer by night.",
      "Stay positive. Test negative.",
      "You are the CSS to my HTML.",
      "Ctrl + Alt + Delete is my cardio.",
      "Geeks rule the world.",
      "I'm the admin, that's why.",
      "I speak fluent hexadecimal.",
      "I'm not antisocial, I'm just not user-friendly.",
      "Resistance is futile.",
      "I'm not a robot, but I speak their language.",
      "Geek is the new chic.",
      "I'm not old, I'm vintage.",
      "Buffering my way through life.",
      "My other computer is a data center.",
      "I'm silently judging your font choice.",
      "Will code for coffee.",
      "Ctrl+S before you Ctrl+W.",
      "May your code compile and your coffee be strong.",
      "It works on my machine.",
      "I'm not a hacker, I just know many shortcuts.",
      "Geek is just a word, until you own it.",
      "I code, therefore I am.",
      "Nerds are cool.",
      "Keep coding and carry on.",
      "The geeks shall inherit the Earth.",
      "In code we trust.",
      "I'm debugging you in my mind.",
      "Objects in the mirror are nerdier than they appear.",
      "There's no app for that.",
      "I'm not a complete idiot, some parts are missing.",
      "The only constant is change (and your bugs).",
      "All your base are belong to us.",
      "Geek inside.",
      "My code doesn't always work, but when it does, I'm still in shock.",
      "Geeking out!",
      "I'm not lazy, I'm just on energy-saving mode.",
      "Geek and proud.",
      "Talk binary to me.",
      "I'm not staring at a screen, I'm looking into the future.",
      "I put the 'tech' in technique.",
      "I'm not ignoring you, I'm just prioritizing my tasks.",
      "Geek by nature, gamer by choice.",
      "I'm not a nerd, I'm a specialist.",
      "I'm not random, you just can't predict me.",
      "I have too many tabs open in my mind.",
      "404: Sarcasm not found.",
      "Ctrl+Z enthusiast.",
      "Code blooded.",
      "I'm a web developer, not a magician.",
      "I'm not late, I'm on developer time.",
      "Will work for bandwidth.",
      "I'm not antisocial, I'm selectively social.",
      "Geek is the new sexy.",
      "I'm not bossy, I just have better ideas.",
      "Geek and loving it.",
      "I'm not arguing, I'm just explaining why I'm right.",
      "I'm not a control freak, I'm just in control.",
      "I'm not opinionated, I'm just always right.",
      "I don't suffer from insanity, I enjoy every minute of it.",
      "Debugging is like being the detective in a crime movie where you're also the murderer.",
      "I'm not a programmer, I just play one on the computer.",
      "Will debug for chocolate.",
      "I'm not clumsy, my code is just too intelligent.",
      "I'm not a geek, I'm just good with computers.",
      "My code's so clean, you could eat off it.",
      "I don't need Google, my code knows everything.",
      "I'm not a superhero, but I am a code hero.",
      "It's not procrastination, it's thinking time.",
      "I'm not ignoring you, I'm in stealth mode.",
      "I'm not multitasking, I'm just task-switching.",
      "I'm not a techie, I'm a magician.",
      "I don't make mistakes, I have debugging moments.",
      "My life is a series of ones and zeros.",
      "I'm not anti-social, I'm pro-solitude.",
      "I'm not a geek, I'm a level 12 paladin.",
      "I don't need a user manual, I am the manual.",
      "I don't need a debugger, my code never has bugs.",
      "I'm not a wizard, but I code like one.",
      "I'm not ignoring you, I'm just prioritizing my backlog.",
      "I'm not lost, my GPS just has a bug.",
      "I'm not offline, I'm just on a different frequency.",
      "I don't snore, I dream of code.",
      "I'm not a gamer, I'm a virtual reality expert.",
      "I don't need a map, my code navigates the world.",
      "I'm not stubborn, my code is just resilient.",
      "I don't get lost, the world is just uncharted territory.",
      "I'm not a machine, but my code is flawless.",
      "I don't need social skills, I have Wi-Fi.",
      "I'm not distracted, I'm just exploring alternate universes.",
      "I'm not old, I'm just using a legacy system.",
      "I'm not a developer, I'm an architect of digital worlds."  
    ] 
  },
  { id: 17,
    name: 'Binary',
    sentences: [
      "1",
      "0"     
  ]
  },
  { id: 18,
    name: 'Groot',
    sentences: [
      "Groot",
      "I Groot",
      "I'm Groot",
      "I am Groot"     
  ]
  },

]

export default ipsums