export const bidenIpsum = [
  "We choose truth over facts.",
  "Poor kids are just as bright and just as talented as white kids.",
  "You got more questions? But I tell you, if you have a problem figuring out whether you're for me or Trump, then you ain't black.",
  "We cannot let this, we've never allowed any crisis from the Civil War straight through to the pandemic of '17, all the way around, '16, we have never, never let our democracy sakes second fiddle, way they, we can both have a democracy and ... correct the public health.",
  "I'm beginning to see why your wife left you.",
  "You're a lying dog-faced pony soldier.",
  "Look, fat, here's the deal...",
  "I got hairy legs that turn blonde in the sun and the kids used to reach in the pool and rub my leg down so it was straight and then watch the hair come back up again.",
  "If you have a problem figuring out whether you're for me or Trump, then you ain't black.",
  "We all these truths to be self-evident. All men and women created by go—you know, you know the thing.",
  "And by the way, you know, I sit on the stand, and it'd get hot. I got hairy legs that turn blonde in the sun.",
  "You know, the rapidly rising, uh, uh, in with, uh, with, uh, I don't know.",
  "Why why why why why why why why are we waiting? You know, we owe these truths to be self-evident. All men and women created by, go, you know the thing.",
  "What kind of country are we going to be? Four more years of George, uh, he uh, gonna find ourselves in a position where, if Trump gets elected, uh, we're gonna be, uh, we're gonna be in a different world.",
  "We're gonna put y'all back in chains.",
  "I'm Joe Biden's husband, Joe Biden.",
  "I would eliminate the Trump tax cuts.",
  "I'm prepared to say that I have a record over 40 years, and that I'm going to beat Joe Biden.",
  "We have to take care of the cure. That will make the problem worse no matter what.",
  "Make sure you have the record player on at night.",
  "I'm not going nuts.",
  "I'm the Vice President of the United States.",
  "Look, here's the deal.",
  "I think he [Trump] should not remain as president.",
  "You're trying your breast, but it never feels like enough.",
  "The good news is, for me, I'm here. The bad news for you is, I'm coming back.",
  "We have to do more than just build back better. We have to build back better.",
  "I'm running as a proud Democrat for the Senate.",
  "I'm the Democratic Party's candidate for the United States Senate.",
  "When I was 17, I interned with a guy named Ed Muskie, who was running for president of the United States.",
  "They'll shoot me. They'll shoot me. They'll shoot me in the head. They'll shoot the other guy. And they'll be rid of us both. I am not joking.",
  "A Harris-Biden administration is gonna relaunch that effort.",
  "We need to act like we're in a national emergency. We gotta get on with it.",
  "If you could take care, if you were a quartermaster, you can sure in hell take care runnin' a, you know, a department store uh, thing, you know, where, in the second floor of the ladies' department or whatever, you know what I mean?",
  "I'm Joe Biden, I'm a Democratic candidate for the United States Senate.",
  "You're trying your breast, but it never feels like enough.",
  "I'm beginning to get bored. I mean, you know, everybody's been incredibly polite, but, you know, it's getting a little dull. You guys used to ask me all these great questions.",
  "We can only re-elect Donald Trump.",
  "I tell you, if you have a problem figuring out whether you're for me or Trump, then you ain't black.",
  "You know, there's a, uh, during World War II, uh, you know, where Roosevelt came up with a thing, that, uh, you know, was totally different than a, than the, the, it's called, he called it, the, you know, the World War II, he had the war ... the war production board.",
  "We're going to impose the largest tax increase in history.",
  "I may be a white boy, but I can jump.",
  "I've done some dumb things, and I'll do dumb things again.",
  "I'd be delighted to sit down and compare my IQ to yours, if you'd like.",
  "You cannot go to a 7-Eleven or a Dunkin' Donuts unless you have a slight Indian accent. I'm not joking.",
  "We got to talk about 'liddle' kids jumping on my lap.",
  "I'm sorry, I'm about to end, but you know, if you want to talk about, um, a few more things.",
  "He [Obama] called me ‘Barack’. I said, 'I’m Joe, Mr. President.'",
  "The only people who will be able to drink Starbucks premium, black coffee with no sugar, no cream is gonna be white people.",
  "My name's Joe Biden. I'm a Democratic candidate for the United States Senate.",
  "I learned about roaches. I learned about kids jumping on my lap, and I love kids jumping on my lap.",
  "In the 2020 census, which is now two censuses ago...",
  "You know the rapidly rising um, uh, in with uh, with uh, I don't know, uh."
]

export const bostonianIpsum = [
  "Pahk the cah in Hahvahd Yahd.",
  "I went to Dunkin' for a regulah cuppa coffee.",
  "Did ya catch the Red Sox game last night?",
  "Hey, can you pass me a bowl of chowdah?",
  "The T is wicked slow during rush hour.",
  "Let's grab some lobstah rolls down by the shaw.",
  "I'm wicked smaht, I graduated from MIT.",
  "The wicked pissah pahk is down by the rivah.",
  "I'm heading to the packie for some beeahs.",
  "I love the swan boats in the Public Garden.",
  "The Boston Marathon is wicked hahd.",
  "I saw Ben Affleck at the Bahneyahd.",
  "Hey, do you want some cannolis from Mike's Pastry?",
  "I'm wicked excited for the St. Patrick's Day parade.",
  "I can't find my cah keys, they're probably in the bubblah.",
  "The Bruins game was a real nail-bitah.",
  "The Prudential Center has wicked good shoppin'.",
  "I had a wicked good time at the Boston Tea Party Ships.",
  "I got a wicked bad sunburn at Revere Beach.",
  "I saw a guy in a penguin suit waddlin' around Fanueil Hall.",
  "Let's take a duck tour around the city.",
  "I'm wicked tired from shovelin' all that snow.",
  "The Zakim Bridge is wicked impressive.",
  "I'm goin' to the Sox game, want me to get ya a Fenway Frank?",
  "The chowdah at Legal Sea Foods is wicked tasty.",
  "I can't believe how cold it is in the middle of June.",
  "I saw Matt Damon filmin' a movie in the North End.",
  "I'm gonna have a wicked good time at the Harpoon Brewery.",
  "I love takin' a stroll along the Charles Rivah Esplanade.",
  "I'm headin' to the Cape for a wicked relaxin' weekend.",
  "The Swan Boats are wicked fun for the kids.",
  "I had a wicked bad case of the Mondays.",
  "I got stuck in traffic on the Pike for like forevah.",
  "I'm wicked excited for the New England Patriots game.",
  "I'm meetin' my friends at Cheers for a pint.",
  "The USS Constitution is a wicked cool ship.",
  "The Bunker Hill Monument is wicked tall.",
  "I love takin' a stroll on Castle Island.",
  "I'm gonna go get a cannoli at Modern Pastry.",
  "The Sam Adams brewery tour is wicked fun.",
  "I saw a wicked awesome street performer in Quincy Market.",
  "The North End has the best Italian food in the city.",
  "I saw a guy walkin' his pet lobster down Newbury Street.",
  "I'm wicked excited for the Head of the Charles Regatta.",
  "I'm gonna go to the Cape and get some beach time.",
  "I love takin' the ferry to Martha's Vineyard.",
  "I'm gonna go shoppin' on Newbury Street.",
  "The Sam Adams Boston Lager is wicked good.",
  "I'm gonna go see the Celtics game at the Garden.",
  "I'm gonna go watch the Boston Pops perform on the Esplanade.",
  "I'm wicked excited for the Tall Ships Festival.",
  "I'm gonna go see the Bruins game at the TD Garden.",
  "I'm wicked excited for the Boston Calling Music Festival.",
  "I'm gonna go get a lobster roll at Neptune Oyster.",
  "I saw a guy jugglin' fire outside Quincy Market.",
  "I love watchin' the swans swim in the Public Garden pond.",
  "I'm wicked excited for the Boston Marathon.",
  "I'm gonna go get some clam chowdah at Union Oyster House.",
  "I love watchin' the sailboats on the Charles Rivah.",
  "I'm wicked excited for the St. Patrick's Day parade in Southie.",
  "I'm gonna go get a lobster roll at James Hook & Co.",
  "I'm gonna go see the fireworks on the Charles Rivah Esplanade.",
  "I'm wicked excited for the Big E fair in Springfield.",
  "I'm gonna go get some oysters at Island Creek Oyster Bar.",
  "I'm gonna go see a concert at the House of Blues.",
  "I'm wicked excited for the Boston Calling Music Festival at City Hall Plaza.",
  "I'm gonna go get some clam chowdah at Legal Sea Foods.",
  "I love watchin' the sunset from the top of the Prudential Center.",
  "I'm wicked excited for the St. Patrick's Day parade in South Boston.",
  "I'm gonna go get a lobster roll at B&G Oysters.",
  "I love watchin' the street performers in Harvard Square.",
]

export const conservativeIpsum = [
  "Small government, big freedom.",
  "Hard work pays off.",
  "Lower taxes, higher growth.",
  "Individual liberty above all.",
  "Traditional values matter.",
  "Free markets drive prosperity.",
  "Limited government, unlimited potential.",
  "Personal responsibility leads to success.",
  "Conserving our constitutional rights.",
  "Strong defense protects freedom.",
  "Fiscal responsibility breeds stability.",
  "Family is the cornerstone of society.",
  "Respecting the rule of law.",
  "Entrepreneurship drives innovation.",
  "Less regulation, more opportunity.",
  "Equality of opportunity, not outcome.",
  "Faith in God, faith in America.",
  "Preserving our heritage for future generations.",
  "Free speech is non-negotiable.",
  "Individual rights trump collective demands.",
  "Secure borders protect national sovereignty.",
  "Character and integrity matter.",
  "Merit-based rewards promote excellence.",
  "Patriotism is not outdated.",
  "Respecting our military and veterans.",
  "The Constitution is our guiding light.",
  "Conservative principles withstand the test of time.",
  "Education starts at home.",
  "Work hard, play by the rules.",
  "Lower government intervention, higher prosperity.",
  "America is the land of opportunity.",
  "Less dependency, more self-reliance.",
  "Conservative values build strong communities.",
  "Government should be accountable to the people.",
  "Welfare should be a temporary hand-up, not a handout.",
  "Individualism over collectivism.",
  "Respecting the sanctity of life.",
  "Limited entitlements, maximum freedom.",
  "Common sense, not government control.",
  "Market competition fuels progress.",
  "Protecting the rights of the unborn.",
  "Less bureaucracy, more efficiency.",
  "The free market is the best regulator.",
  "Conserving natural resources responsibly.",
  "Protecting traditional marriage and family.",
  "Smaller government, bigger individuality.",
  "Personal freedom, limited government intrusion.",
  "Freedom of speech, even when unpopular.",
  "Conservatism empowers the individual.",
  "Preserving the Second Amendment rights.",
  "Liberty requires eternal vigilance.",
]

export const cowboyIpsum = [
  "Happy trails!",
  "Ride 'em cowboy!",
  "Saddle up and hold on tight.",
  "There's a new sheriff in town.",
  "Yeehaw!",
  "Keep your powder dry.",
  "Don't squat with your spurs on.",
  "Ain't nothin' better than the smell of leather.",
  "Never trust a man who doesn't wear a hat.",
  "Time to hit the dusty trail.",
  "Don't count your chickens before they're hatched.",
  "This town ain't big enough for the both of us.",
  "As the crow flies.",
  "Easy as pie.",
  "Hold your horses.",
  "Tougher than a two-dollar steak.",
  "Giddy up!",
  "Don't fence me in.",
  "The early bird gets the worm.",
  "Lasso your dreams.",
  "Don't talk big on an empty belly.",
  "Take the bull by the horns.",
  "Home on the range.",
  "Riding off into the sunset.",
  "The wind at your back and the sun on your face.",
  "A cowboy is a man with guts and a horse.",
  "Live by the saddle, die by the saddle.",
  "Stay on the straight and narrow.",
  "Ain't no use in frettin' over spilled milk.",
  "The only way out is through.",
  "Rope 'em, tie 'em, brand 'em.",
  "Give it all you've got, then give some more.",
  "Mind your Ps and Qs.",
  "Don't let the dust settle under your boots.",
  "Ain't no sense in bawlin' over spilt milk.",
  "Ain't no rest for the wicked.",
  "Never look a gift horse in the mouth.",
  "The old cowpoke still has some tricks up his sleeve.",
  "Saddle sores and calloused hands make a cowboy.",
  "Better to be a has-been than a never-was.",
  "Luck is what happens when preparation meets opportunity.",
  "Don't let your mouth write checks your body can't cash.",
  "Steady as she goes.",
  "Like a tumbleweed in the wind.",
  "The sun's always shining above the clouds.",
  "When in doubt, let your horse do the thinkin'.",
  "Don't squat on your spurs.",
  "Ride the high country.",
  "Life is tough, but cowboys are tougher.",
  "Never give a wolf an even chance.",
  "Stay true to your roots.",
  "Saddle sores are badges of honor."
]

export const gamerIpsum = [
  "Game on!",
  "Level up!",
  "Stay frosty!",
  "Ready, set, go!",
  "Time to pwn!",
  "Get in the game!",
  "Keep calm and game on.",
  "Press start to begin.",
  "Respawn in progress.",
  "Victory awaits!",
  "Game over, man!",
  "The grind never ends.",
  "Aim high, shoot true.",
  "Gameplay or it didn't happen.",
  "Born to play.",
  "No lag, no mercy.",
  "One more round!",
  "Can't stop, won't stop.",
  "Game face on.",
  "In pixels we trust.",
  "Rage quit in 3... 2... 1...",
  "The legend begins.",
  "Gameplay is my cardio.",
  "Reload, reload, reload.",
  "Achievement unlocked!",
  "Ready for epicness!",
  "Glitch in the matrix.",
  "Play like a pro.",
  "Bring on the challenge!",
  "Game night is the best night.",
  "Enter the virtual realm.",
  "Keep your friends close and your enemies laggy.",
  "Gaming is life.",
  "Noob, but learning.",
  "Game over? Just one more time.",
  "Welcome to the digital battlefield.",
  "Power-up and dominate.",
  "Keep your head in the game.",
  "Unlock your potential.",
  "Gaming: where dreams come true.",
  "Pixelated adventures await.",
  "Game over is not an option.",
  "Game hard or go home.",
  "Respawn and conquer.",
  "Game with passion.",
  "Stay sharp, stay alive.",
  "Gameplay is an art.",
  "It's dangerous to go alone!",
  "Play smarter, not harder.",
  "Leveling up in progress.",
  "The gamer's creed: Play. Explore. Conquer."
]

export const geekIpsum = [
  "Talk nerdy to me.",
  "I'm not a nerd, I'm just intellectually gifted.",
  "Nerds rule the world.",
  "Geek is the new cool.",
  "May the source code be with you.",
  "Debugging is like being the detective in a crime movie where you're also the murderer.",
  "I'm not lazy, I'm just buffering.",
  "There are only 10 types of people in the world: Those who understand binary, and those who don't.",
  "Error 404: Sense of humor not found.",
  "In binary, I love you is 01001100 01101111 01110110 01100101 00100000 01111001 01101111 01110101.",
  "I don't need a superhero. I have Wi-Fi.",
  "I'm not antisocial; I'm just not user-friendly.",
  "I'm not a geek. I'm a level 12 paladin.",
  "I'm not lazy, I'm on energy-saving mode.",
  "There's no place like 127.0.0.1",
  "All I need is coffee and coding.",
  "Geek by day, superhero by night.",
  "I'm not weird, I'm limited edition.",
  "Keep calm and trust the algorithm.",
  "I'm so nerdy, I use Pi as a pick-up line.",
  "You had me at 'Hello, World!'",
  "Sleep is just a socially acceptable simulation of death.",
  "I'm not awkward, I'm just navigating a new social interface.",
  "When in doubt, Ctrl+Alt+Delete.",
  "I'm not lazy, I'm in power-saving mode.",
  "I speak HTML, CSS, and JavaScript fluently.",
  "I code, therefore I am.",
  "The cake is a lie.",
  "I'm silently correcting your grammar.",
  "I'm not lazy, I'm just highly efficient.",
  "I'm not a nerd; I'm a human search engine.",
  "There's no app for that.",
  "I find your lack of coding skills disturbing.",
  "I don't get older; I upgrade.",
  "I'm not a geek; I'm a pixel magician.",
  "I'm not clumsy; the floor just hates me.",
  "I'm not antisocial; I'm just socially selective.",
  "Keep calm and code on.",
  "I'm not a nerd; I'm just intellectually curious.",
  "I'm not a geek; I'm a digital pioneer.",
  "99 bugs in the code, 99 bugs in the code. Take one down, patch it around, 127 bugs in the code.",
  "I can resist everything except temptation... and coding.",
  "I'm not lazy; I'm just on my energy-saving mode.",
  "I don't need Google; my brain is a search engine.",
  "There's no place like 127.0.0.1.",
  "I'm not weird; I'm a limited edition.",
  "I'm not antisocial; I'm just socially awkward.",
  "Keep calm and trust the programmer.",
  "I'm not lazy; I'm just highly efficient.",
  "I'm not a nerd; I'm an intellectual badass.",
  "I'm silently correcting your code.",
  "I'm not clumsy; I'm just in beta testing.",
  "I'm not antisocial; I'm just selectively social."
]

export const harryPotterIpsum = [
  "I solemnly swear that I am up to no good.",
  "Expecto Patronum!",
  "After all this time? Always.",
  "It does not do to dwell on dreams and forget to live.",
  "Dark times lie ahead of us, and there will be a time when we must choose between what is easy and what is right.",
  "Happiness can be found even in the darkest of times if one only remembers to turn on the light.",
  "The ones that love us never really leave us.",
  "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
  "Not all treasure is silver and gold, mate.",
  "Help will always be given at Hogwarts to those who ask for it.",
  "We've all got both light and dark inside us. What matters is the part we choose to act on.",
  "To the well-organized mind, death is but the next great adventure.",
  "It is our choices that show what we truly are, far more than our abilities.",
  "Words are, in my not-so-humble opinion, our most inexhaustible source of magic.",
  "It does not do well to dwell on dreams and forget to live.",
  "We must all face the choice between what is right and what is easy.",
  "The ones that love us never really leave us.",
  "Just because you have the emotional range of a teaspoon doesn't mean we all have.",
  "It matters not what someone is born, but what they grow to be.",
  "You're a wizard, Harry.",
  "Wit beyond measure is man's greatest treasure.",
  "To the well-organized mind, death is but the next great adventure.",
  "Numbing the pain for a while will make it worse when you finally feel it.",
  "We're all human, aren't we? Every human life is worth the same and worth saving.",
  "Differences of habit and language are nothing at all if our aims are identical and our hearts are open.",
  "It takes a great deal of bravery to stand up to your enemies, but a great deal more to stand up to your friends.",
  "It is the unknown we fear when we look upon death and darkness, nothing more.",
  "Curiosity is not a sin, but we should exercise caution with our curiosity.",
  "Indifference and neglect often do much more damage than outright dislike.",
  "We must try not to sink beneath our anguish, Harry, but battle on.",
  "It is the quality of one's convictions that determines success, not the number of followers.",
  "It is impossible to manufacture or imitate love.",
  "Things we lose have a way of coming back to us in the end, if not always in the way we expect.",
  "Age is foolish and forgetful when it underestimates youth.",
  "We are only as strong as we are united, as weak as we are divided.",
  "It is a curious thing, Harry, but perhaps those who are best suited to power are those who have never sought it.",
  "It is a strange thing, but when you are dreading something, and would give anything to slow down time, it has a disobliging habit of speeding up.",
  "It is the unknown we fear when we look upon death and darkness, nothing more.",
  "We do not need magic to change the world. We carry all the power we need inside ourselves already.",
  "You sort of start thinking anything's possible if you've got enough nerve.",
  "It is the unknown we fear when we look upon death and darkness, nothing more.",
  "The best of us sometimes eat our words.",
  "Indifference and neglect often do much more damage than outright dislike.",
  "There are some things you can't share without ending up liking each other, and knocking out a twelve-foot mountain troll is one of them.",
  "The mind is not a book, to be opened at will and examined at leisure.",
  "Greatness inspires envy, envy engenders spite, spite spawns lies.",
  "To have been loved so deeply, even though the person who loved us is gone, will give us some protection forever.",
  "We've all got both light and dark inside us. What matters is the part we choose to act on.",
  "It is our choices, Harry, that show what we truly are, far more than our abilities.",
  "To the well-organized mind, death is but the next great adventure.",
  "Numbing the pain for a while will make it worse when you finally feel it."
]

export const hipsterIpsum = [
  "Craft beer irony 8-bit.",
  "Tote bag biodiesel flannel.",
  "Organic kale chips ennui.",
  "Polaroid DIY fanny pack.",
  "Farm-to-table tattooed quinoa.",
  "Artisanal typewriter messenger bag.",
  "Vinyl sustainable locavore.",
  "Beard trust fund chambray.",
  "Vintage bicycle PBR&B.",
  "Avocado toast cardigan aesthetic.",
  "Sustainable leggings gluten-free.",
  "Hand-poured soy candle heirloom.",
  "Meditation kombucha Tumblr.",
  "Roof party YOLO cold-pressed.",
  "Mustache cronut ethical.",
  "Vegan brunch plaid.",
  "Lumbersexual bespoke dreamcatcher.",
  "Artisan coffee skateboard.",
  "Edison bulb bicycle rights.",
  "Taxidermy banh mi flexitarian.",
  "Gluten-free VHS sriracha.",
  "Freegan selvage kale chips.",
  "Chia seed irony messenger bag.",
  "Vice master cleanse cray.",
  "Portland slow-carb activated charcoal.",
  "Narwhal fashion axe kitsch.",
  "Ethical drinking vinegar cliche.",
  "Pitchfork irony hoodie.",
  "Copper mug succulents.",
  "Fingerstache PBR&B biodiesel.",
  "Dreamcatcher Helvetica normcore.",
  "DIY craft beer forage.",
  "Skateboard tousled tofu.",
  "Lo-fi four loko umami.",
  "Sriracha swag selfies.",
  "Cold-pressed shabby chic.",
  "Single-origin coffee tattooed.",
  "Pinterest flannel Kickstarter.",
  "Hella organic kombucha.",
  "Raw denim deep v.",
  "Freegan tousled artisan.",
  "Austin gentrify chambray.",
  "Sustainable meditation irony.",
  "Retro chillwave typewriter.",
  "Vegan leggings beard.",
  "Artisan biodiesel beard.",
  "Plaid cliche umami.",
  "Normcore YOLO seitan.",
  "Chia seed messenger bag.",
  "Cardigan sriracha Thundercats.",
  "Disrupt chambray roof party.",
  "Taxidermy Tumblr dreamcatcher.",
  "Paleo cornhole beard.",
  "Irony gastropub craft beer.",
  "Farm-to-table artisan PBR&B.",
  "Flexitarian skateboard locavore.",
  "Trust fund hoodie irony.",
  "DIY tattooed sustainable.",
  "Mixtape aesthetic Wes Anderson.",
  "Gluten-free cardigan beard.",
  "Fixie forage typewriter.",
  "PBR&B VHS cronut.",
  "Flannel single-origin skateboard.",
  "Kitsch kale chips Pitchfork.",
  "Succulents tattooed gastropub.",
  "Chillwave taxidermy Thundercats.",
  "Selvage meditation heirloom.",
  "Bicycle rights tofu normcore.",
  "Paleo vinyl kombucha.",
  "Hella skateboard artisan.",
  "Craft beer irony 8-bit.",
  "Tote bag biodiesel flannel.",
  "Organic kale chips ennui.",
  "Polaroid DIY fanny pack."
]

export const hockeyIpsum = [
  "He's got soft hands around the net.",
  "That was a filthy dangle!",
  "He's got wheels; he's so fast on the ice.",
  "The goalie stood on his head to make that save.",
  "He got sniped top shelf.",
  "He dropped the mitts and threw some haymakers.",
  "That was a beauty pass!",
  "He's got silky smooth hands.",
  "The ref missed a blatant trip there.",
  "The puck took a weird bounce off the boards.",
  "He got undressed by a deke.",
  "The defenseman pinched in and scored.",
  "He went bar down on that shot.",
  "That was a huge slapper from the point.",
  "The goalie made a pad save.",
  "He's a grinder, always working hard in the corners.",
  "The playmaker set up a beautiful one-timer.",
  "He's a dangler; his stickhandling is incredible.",
  "The enforcer dropped the gloves and started a fight.",
  "The goalie made a desperation diving save.",
  "The coach benched him for taking a dumb penalty.",
  "He took a clapper from the blue line.",
  "The forward backchecked and stole the puck.",
  "He got robbed by the goalie's glove save.",
  "The team is in the offensive zone, cycling the puck.",
  "He's got a wicked snapshot.",
  "He went five-hole and scored!",
  "The defenseman blocked a shot with his body.",
  "He's got a cannon of a slapshot.",
  "The team is on the penalty kill.",
  "The goalie made a stick save.",
  "He got caught cherry-picking at the opponent's blue line.",
  "The forward got a breakaway and scored on a backhand.",
  "The ref called a hooking penalty.",
  "The goalie made a toe save to keep the game tied.",
  "He's got great hockey IQ; he always makes smart plays.",
  "He's a crease crasher; he scores a lot of garbage goals.",
  "The player took a misconduct penalty for arguing with the ref.",
  "The goalie made a kick save with his pad.",
  "He got decked with a huge open-ice hit.",
  "He sniped it top corner with a wrister.",
  "The forward made a saucer pass over the defenseman's stick.",
  "He got stoned by the goalie on a breakaway.",
  "The defenseman laid out a big hit along the boards.",
  "The player got called for a high-sticking penalty.",
  "The goalie made a blocker save on a hard shot.",
  "He's a pest, always getting under the opponents' skin.",
  "The player took a tripping penalty.",
  "He got completely undressed by a toe drag move.",
  "The team is on a power play.",
  "He made a diving poke check to break up the play.",
  "The goalie made a flashy glove save.",
  "He's a sniper; he has a deadly accurate shot.",
  "The defenseman cleared the puck out of the zone.",
]

export const liberalIpsum = [
  "Equality for all, not just for some.",
  "Diversity makes us stronger.",
  "Injustice anywhere is a threat to justice everywhere.",
  "Love is love, no matter who you are.",
  "Empathy is the cornerstone of a compassionate society.",
  "The power of the people can overcome any obstacle.",
  "Together we rise, divided we fall.",
  "Education is a right, not a privilege.",
  "Healthcare is a basic human right.",
  "Progress comes from open minds and open hearts.",
  "Speak truth to power.",
  "A society is judged by how it treats its most vulnerable members.",
  "Science and reason should guide our decisions.",
  "No human is illegal.",
  "Invest in people, not in walls.",
  "Peace is the path to prosperity.",
  "Climate change is real; let's act now.",
  "Fight for a fair and living wage.",
  "Everyone deserves a seat at the table.",
  "Protect the rights of workers.",
  "Access to clean water is a fundamental right.",
  "Freedom of speech is a cornerstone of democracy.",
  "Vote like your rights depend on it—because they do.",
  "Choose hope over fear.",
  "Stand up for women's rights.",
  "Celebrate our differences; they make us unique.",
  "Protect our planet for future generations.",
  "Listen to understand, not just to respond.",
  "Reject bigotry in all its forms.",
  "Support renewable energy for a sustainable future.",
  "Invest in public infrastructure and services.",
  "Treat others with kindness and respect.",
  "Challenge the status quo for progress.",
  "Advocate for affordable housing for all.",
  "Invest in early childhood education.",
  "Promote transparency and accountability in government.",
  "Combat systemic racism and discrimination.",
  "Protect the right to vote for all citizens.",
  "Promote gun control measures for safer communities.",
  "Invest in mental health support and resources.",
  "Fight for reproductive rights and bodily autonomy.",
  "Peaceful protests can bring about change.",
  "Stand up against income inequality.",
  "Foster a culture of inclusivity and acceptance.",
  "Believe in the power of collective action.",
  "Stand with refugees and those seeking asylum.",
  "Advocate for criminal justice reform.",
  "Promote responsible and sustainable business practices.",
  "Challenge corporate influence in politics.",
  "Invest in arts and culture for a vibrant society."
]

export const newYorkerIpsum = [
  "I'm gonna grab a slice and catch the train.",
  "Fuhgeddaboudit! That idea won't fly here.",
  "Hey, watch out for the potholes on this block.",
  "I need my coffee, or I'll be cranky all day.",
  "Let's hit up Times Square and see the lights.",
  "This bagel is the real deal, no imitation stuff.",
  "I can't believe the subway is delayed again.",
  "Get a hot dog from the street vendor, it's a classic.",
  "You got any spare change for a pretzel?",
  "I'm meeting my friends at the bodega later.",
  "The Knicks finally won a game, can you believe it?",
  "I'll take a dirty water dog with mustard, please.",
  "This pizza is legit, just like back in the Bronx.",
  "I need to find a decent slice joint in this neighborhood.",
  "Don't forget to swipe your MetroCard before boarding.",
  "I love walking through Central Park in the fall.",
  "The Empire State Building is a must-see tourist spot.",
  "I can't decide between a bagel or an egg sandwich.",
  "Take a walk along the High Line, it's beautiful.",
  "The hot dog cart is the heart of New York street food.",
  "Let's grab a cold one at the local dive bar.",
  "The Statue of Liberty is an iconic symbol of freedom.",
  "I'll grab a slice to go, I'm in a hurry.",
  "Don't jaywalk, the cops are cracking down on it.",
  "I'm craving some dollar pizza, the ultimate cheap eat.",
  "The Empire State Building offers stunning views.",
  "There's a street fair happening in Chelsea this weekend.",
  "I'm taking the A train up to Harlem for a concert.",
  "I'll have a chopped cheese sandwich, extra mayo.",
  "New York bagels are just on another level.",
  "I'm gonna catch a Broadway show tonight, it's a must-do.",
  "Let's grab a cup of joe at the corner deli.",
  "I'll meet you in front of the Flatiron Building.",
  "You should try a pastrami sandwich from Katz's Deli.",
  "This neighborhood has a real old-school vibe.",
  "I love strolling through Greenwich Village on weekends.",
  "Don't forget your umbrella, it's gonna rain cats and dogs.",
  "I'll have a slice with pepperoni and extra cheese.",
  "This neighborhood is gentrifying pretty quickly.",
  "The hot dog guy on 42nd Street makes the best dogs.",
  "I'm gonna grab a taxi, I don't feel like taking the subway.",
  "Let's take the Staten Island Ferry for a scenic ride.",
  "I'm going to the bodega to grab some snacks for the game.",
  "The street performers in Union Square are always entertaining.",
  "I'll have a knish with mustard, please.",
  "I'm heading to Coney Island for some beach time.",
  "The view from the Top of the Rock is breathtaking.",
  "I need a slice of pizza to cure this hangover.",
  "I'm gonna catch the L train to Williamsburg.",
  "Let's take a walk across the Brooklyn Bridge.",
  "I'm meeting my date at the speakeasy downtown.",
  "The Halal guys have the best chicken and rice platters.",
];

export const pirateIpsum = [
  "Avast ye, matey!",
  "Shiver me timbers!",
  "Yo ho ho and a bottle of rum!",
  "Sail ho!",
  "Batten down the hatches!",
  "Ahoy, me hearties!",
  "Blow me down!",
  "Walk the plank!",
  "Dead men tell no tales.",
  "Thar she blows!",
  "Aye, aye, captain!",
  "Hoist the Jolly Roger!",
  "Scurvy dog!",
  "X marks the spot!",
  "Land ho!",
  "Aye, me bucko!",
  "Prepare to be boarded!",
  "Davy Jones' locker awaits!",
  "A pirate's life for me!",
  "Arr, me matey!",
  "Savvy?",
  "Pieces of eight!",
  "Cap'n says so!",
  "Thar be treasure!",
  "Avast, ye landlubber!",
  "Sink me!",
  "By Blackbeard's beard!",
  "To the depths of the sea!",
  "Thar be rough waters ahead!",
  "Aye, the wind be at our backs!",
  "Set sail for adventure!",
  "No prey, no pay!",
  "Curses upon ye!",
  "A pirate never reveals his secrets.",
  "All hands on deck!",
  "Splice the mainbrace!",
  "Aye, the sea be a cruel mistress.",
  "A gold doubloon for your thoughts!",
  "Raise the anchor!",
  "Avast, me hearties, for a jolly good time!",
  "May your compass always point true!",
  "Beware the Kraken!",
  "Fair winds and following seas!",
  "Aye, the pirate's life be the only life!",
  "Avast, ye scurvy landlubbers!",
  "Aye, the rum be gone!",
  "Take what ye can, give nothin' back!",
  "In the heart of a pirate beats the soul of a free man!",
  "Aye, the open sea calls to me!",
  "Thar be adventure on the horizon!",
  "A pirate's treasure is never far away!",
  "Yo ho ho! We sail for glory!"
]

export const rastaIpsum = [
  "One love, one heart, one destiny.",
  "Don't worry about a thing, 'cause every little thing gonna be all right.",
  "In the abundance of water, the fool is thirsty.",
  "Emancipate yourselves from mental slavery; none but ourselves can free our minds.",
  "Live for yourself, and you will live in vain. Live for others, and you will live again.",
  "The biggest coward is a man who awakens a woman's love with no intention of loving her.",
  "Open your eyes, look within. Are you satisfied with the life you're living?",
  "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.",
  "Rasta don't work for no CIA.",
  "The road of life is rocky, and you may stumble too. So while you point your fingers, someone else is judging you.",
  "Judge not, before you judge yourself.",
  "Better to die fighting for freedom than be a prisoner all the days of your life.",
  "Life is one big road with lots of signs. So when you're riding through the ruts, don't complicate your mind.",
  "Don't gain the world and lose your soul; wisdom is better than silver or gold.",
  "The greatest happiness you can have is knowing that you do not necessarily require happiness.",
  "Don't forget your history, nor your destiny.",
  "Don't be concerned with outward beauty. Be concerned about how beautiful your mind is.",
  "Don't let the distractions of life dull your shine.",
  "The herb is the healing of a nation, alcohol is the destruction.",
  "Love the life you live. Live the life you love.",
  "Don't let the behavior of others destroy your inner peace.",
  "Don't let society tell you how to live.",
  "Every man gotta right to decide his own destiny.",
  "The only way to deal with this life is to accept it.",
  "Don't worry about the future, for tomorrow will worry about itself.",
  "Truth is the light, so you never give up the fight.",
  "Keep calm and smoke ganja.",
  "Don't chase people. Be yourself, do your thing, and work hard. The right people - the ones who really belong in your life - will come to you and stay.",
  "Be the change you want to see in the world.",
  "Don't let Babylon control your mind.",
  "The greatness of a man is not in how much wealth he acquires but in his integrity and his ability to affect those around him positively.",
  "Unity is strength, division is weakness.",
  "Don't forget your roots; they are your foundation.",
  "Don't worry, be happy.",
  "Live good, love more, and laugh often.",
  "Don't be afraid to give up the good and go for the great.",
  "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.",
  "The best way to predict your future is to create it.",
  "Learn the rules so you know how to break them properly.",
  "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Do what you love, love what you do.",
  "Live simply, so that others may simply live.",
  "Don't worry, Jah will provide.",
  "Rise up and conquer your fears.",
  "Don't be a prisoner of your past; it was just a lesson, not a life sentence.",
  "Life is too short to worry about stupid things. Have fun, fall in love, and regret nothing.",
  "Be grateful for small things, big things, and everything in between.",
  "Faith is taking the first step even when you can't see the whole staircase.",
  "Live your life and forget your age.",
  "Don't look back; you're not going that way.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Every day is a chance to change your life.",
]

export const starWarsIpsum = [
  "May the Force be with you.",
  "I have a bad feeling about this.",
  "Do or do not. There is no try.",
  "It's a trap!",
  "I find your lack of faith disturbing.",
  "Help me, Obi-Wan Kenobi. You're my only hope.",
  "The Force will be with you, always.",
  "I am your father.",
  "I've got a bad feeling about this.",
  "A long time ago in a galaxy far, far away...",
  "The Force is strong with this one.",
  "I love you. - I know.",
  "In my experience, there is no such thing as luck.",
  "The dark side of the Force is a pathway to many abilities some consider to be unnatural.",
  "You were the chosen one!",
  "Great, kid. Don't get cocky.",
  "I've got a bad feeling about this.",
  "Never tell me the odds.",
  "It's not my fault!",
  "These aren't the droids you're looking for.",
  "I am a Jedi, like my father before me.",
  "I will finish what you started.",
  "Remember, the Force will be with you, always.",
  "I'm one with the Force. The Force is with me.",
  "The ability to speak does not make you intelligent.",
  "I don't like sand. It's coarse and rough and irritating, and it gets everywhere.",
  "I find your lack of faith disturbing.",
  "There's always a bigger fish.",
  "I'm just a simple man trying to make my way in the universe.",
  "It's treason, then.",
  "So this is how liberty dies... with thunderous applause.",
  "You can't stop the change, any more than you can stop the suns from setting.",
  "I sense a disturbance in the Force.",
  "It's a trap!",
  "I will do what I must.",
  "That's no moon. It's a space station.",
  "You were right about one thing, Master. The negotiations were short.",
  "You were right about me. Tell your sister... you were right.",
  "I'll never turn to the dark side. You've failed, your highness. I am a Jedi, like my father before me.",
  "We're doomed!",
  "He's no good to me dead.",
  "The Force is strong with him. The son of Skywalker must not become a Jedi.",
  "The Force is not a power you have. It's not about lifting rocks. It's the energy between all things, a tension, a balance that binds the universe together.",
  "You can't win, Darth. Strike me down, and I will become more powerful than you could possibly imagine.",
  "Power! Unlimited power!",
  "There is always hope.",
  "Your eyes can deceive you; don't trust them.",
  "A Jedi uses the Force for knowledge and defense, never for attack.",
  "Your focus determines your reality.",
  "It is the quest for honor that makes one honorable.",
  "This is a new day, a new beginning.",
  "The belonging you seek is not behind you; it is ahead.",
  "Let the past die. Kill it if you have to.",
  "I am a Jedi, like my father before me.",
]

export const surferIpsum = [
  "Dude, that wave was gnarly!",
  "Hang ten, bro!",
  "I caught a sick barrel!",
  "The surf's firing today!",
  "Time to wax up and hit the lineup!",
  "Stoked to be shredding some waves!",
  "Cowabunga, dudes!",
  "Tubular ride, man!",
  "Radical cutback on that last wave!",
  "Dropping in on the left, watch out!",
  "Sick bottom turn, bro!",
  "Let's paddle out and catch some bombs!",
  "That wave had some serious juice!",
  "I'm going switch-stance on this one!",
  "The sets are rolling in, epic conditions!",
  "Caught some tasty little peelers out there!",
  "The ocean is my happy place!",
  "I'm going for an air on the next wave!",
  "Cowabunga, baby!",
  "That was a sick floater, dude!",
  "The surf gods are smiling upon us today!",
  "Whoa, did you see that aerial maneuver?!",
  "Just hanging loose and enjoying the ride!",
  "The offshore winds are perfect for surfing!",
  "Dropping in deep and getting barreled!",
  "Time to paddle back out and catch another!",
  "Aloha, my wave-riding brethren!",
  "I'm getting pitted in the green room!",
  "Let's shred this peak together!",
  "Waves for days, life is good!",
  "I'm carving up the face of this wave!",
  "Surfing is my ultimate therapy!",
  "That wave was firing like a freight train!",
  "Dawn patrol session, the best way to start the day!",
  "Epic sunset sesh, can't beat these colors!",
  "Paddle faster, the set is coming!",
  "Just hanging ten and enjoying the ride!",
  "The surf forecast is looking epic!",
  "This wave is a real screamer!",
  "I'm getting pitted, no worries!",
  "Time to bust out some sick tricks!",
  "The ocean is calling, gotta answer!",
  "That wave had a sick wall to it!",
  "I'm in the zone, catching everything in sight!",
  "Let's go for a surfari and explore new breaks!",
  "Surf's up, let's get radical!",
  "Slashing through the lip, feeling the flow!",
  "I'm chasing that endless summer vibe!",
  "Soul surfing is where it's at!",
  "This wave is reeling like a dream!",
  "The sea is my playground, always stoked!",
  "Hooting and hollering for my fellow surfers!"
]

export const trumpIpsum = [
  "Make America Great Again!",
  "I'm really rich.",
  "We will build a wall.",
  "Nobody builds walls better than me.",
  "You're fired!",
  "I have a great relationship with the blacks.",
  "The concept of global warming was created by and for the Chinese.",
  "I have a tremendous amount of energy.",
  "I will be the greatest jobs president that God ever created.",
  "I'm the most successful person ever to run for the presidency.",
  "I love the poorly educated.",
  "My IQ is one of the highest.",
  "I think I am actually humble.",
  "I know words. I have the best words.",
  "You wouldn't believe how bad these people are.",
  "I'm really, really smart.",
  "I've made billions and billions of dollars.",
  "I have so many fabulous friends.",
  "I don't settle for anything.",
  "I think apologizing's a great thing, but you have to be wrong.",
  "I could stand in the middle of Fifth Avenue and shoot somebody, and I wouldn't lose any voters.",
  "I'm not a politician, I'm a businessman.",
  "I love the Mexican people.",
  "We won with poorly educated. I love the poorly educated.",
  "I'm very consistent.",
  "I will be the greatest president that God ever created.",
  "All of the women on 'The Apprentice' flirted with me.",
  "I'm very much a germaphobe.",
  "I have a great relationship with the Mexican people.",
  "I have the best temperament or certainly one of the best temperaments.",
  "The beauty of me is that I'm very rich.",
  "I have a great relationship with African Americans.",
  "I will be the greatest jobs president that God ever created.",
  "I am the least racist person you've ever met.",
  "I've always been successful. I've always been a winner.",
  "I will build a great, great wall on our southern border.",
  "I love China.",
  "Our country is in serious trouble.",
  "We will make America strong again.",
  "I think I am a nice person.",
  "I'm the best thing that's ever happened to the Secret Service.",
  "We're gonna make our country great again.",
  "I will negotiate the best deals.",
  "We will have so much winning if I get elected.",
  "I'm the Ernest Hemingway of 140 characters.",
  "I could be the first presidential candidate to run and make money on it.",
  "I know more about ISIS than the generals do.",
  "I'm very proud of my success.",
  "I love the First Amendment.",
  "I think I'm a really nice guy.",
  "I have a great relationship with the people of Scotland.",
  "I don't wear a toupee.",
];
